### ISSUE TITLE
Connector throws exception when using AppendFilter

### ISSUE THREAD

**Issue by Joao-Garcia-Bras** [streamthoughts/kafka-connect-file-pulse#108]
Hi,

The connector fails when using the append filter to add a new column name. I am using the latest version 1.6.1 as a docker image from dockerhub. Removing the curly brackets from the value, or just setting a hardcoded string results in the same exception.

Config:
```
    "filters"= 'AppendFileName, Row',
    
    "filters.AppendFileName.type"='io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter',
    "filters.AppendFileName.field" = 'FILE_NAME',
    "filters.AppendFileName.value" = '{{ $metadata.name }}',
```

The exception is:

```
java.lang.ClassCastException: class io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression cannot be cast to class io.streamthoughts.kafka.connect.filepulse.expression.PropertyExpression (io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression and io.streamthoughts.kafka.connect.filepulse.expression.PropertyExpression are in unnamed module of loader org.apache.kafka.connect.runtime.isolation.PluginClassLoader @5bbf8daa)
        at io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter.mayEvaluateWriteExpression(AppendFilter.java:113)
        at io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter.apply(AppendFilter.java:81)
        at io.streamthoughts.kafka.connect.filepulse.filter.AbstractMergeRecordFilter.apply(AbstractMergeRecordFilter.java:51)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline$FilterNode.apply(DefaultRecordFilterPipeline.java:159)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:131)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:99)
        at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:169)
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:127)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:289)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:256)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

The full config below:

```
CREATE SOURCE CONNECTOR "oss.file" WITH (
    "connector.class"= 'io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector',
    "tasks.max"= 1,
    "fs.scan.directory.path"= '/data/adr/input',
    "fs.scan.interval.ms"= 10000,
    "fs.scan.filters"= 'io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter',
    "file.filter.regex.pattern"= '^(.*?)',
    "topic"= 'oss.raw',
    "skip.headers"= 1,
    
    "internal.kafka.reporter.bootstrap.servers"= 'broker:29092',
    "internal.kafka.reporter.topic"= 'connect-file-pulse-status',
    "internal.kafka.reporter.id"= 'connect-file-pulse',
    "fs.cleanup.policy.class"= 'io.streamthoughts.kafka.connect.filepulse.clean.MoveCleanupPolicy',
    "cleaner.output.failed.path"= '/data/adr/error',
    "cleaner.output.succeed.path"= '/data/adr/succeed',
    
    "filters"= 'AppendFileName, Row',
    
    "filters.AppendFileName.type"='io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter',
    "filters.AppendFileName.field" = 'FILE_NAME',
    "filters.AppendFileName.value" = '{{ $metadata.name }}',

    "filters.Row.extractColumnName"= 'headers',
    "filters.Row.separator"= ';',
    "filters.Row.trimColumn"= true,
    "filters.Row.type"= 'io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter');
```

**Comment by Joao-Garcia-Bras** [comment]
I managed to fix it, I needed to switch the filter order, so that DelimitedRowFilter goes before AppendFilter.

**Comment by bradydean** [comment]
I'm getting this error but my only filter is the `AppendFilter`.

**Comment by fhussonnois** [comment]
Hi @bradydean, could please copy your configuration ? In addition, which version of FilePulse are you using ?

**Comment by fhussonnois** [comment]
@bradydean, try to change the `filters.path.field` property to `$value.path`.

**Comment by bradydean** [comment]
```
connect-file-pulse                  | io.streamthoughts.kafka.connect.filepulse.expression.accessor.AccessException: Cannot found getter method for attribute 'path' on class 'class io.streamthoughts.kafka.connect.filepulse.source.GenericFileObjectMeta'
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.expression.accessor.ReflectivePropertyAccessor.read(ReflectivePropertyAccessor.java:75)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.expression.accessor.PropertyAccessors.evaluateReaders(PropertyAccessors.java:104)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.expression.accessor.PropertyAccessors.readPropertyValue(PropertyAccessors.java:71)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.expression.PropertyExpression.readValue(PropertyExpression.java:84)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression$ReplacementExpression.readValue(SubstitutionExpression.java:200)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression$ReplacementExpression.readValue(SubstitutionExpression.java:215)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression.readValue(SubstitutionExpression.java:105)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression.readValue(SubstitutionExpression.java:93)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter.apply(AppendFilter.java:89)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.filter.AbstractMergeRecordFilter.apply(AbstractMergeRecordFilter.java:43)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline$FilterNode.apply(DefaultRecordFilterPipeline.java:162)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:134)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:102)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:176)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:199)
connect-file-pulse                  | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:296)
connect-file-pulse                  | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:253)
connect-file-pulse                  | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
connect-file-pulse                  | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:237)
connect-file-pulse                  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
connect-file-pulse                  | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
connect-file-pulse                  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
connect-file-pulse                  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
connect-file-pulse                  | 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by fhussonnois** [comment]
Ok, I get it. The `path` attribute is only available when processing local files. When using the `AmazonS3FileSystemListing` you be able to access `$metadata.uri` attribute (documentation should be updated).

**Comment by fhussonnois** [comment]
Ok, that's an issue. I will provide a fix for that. In meanwhile, I think you can try to access to `$metadata.stringURI`

**Comment by bradydean** [comment]
Sweet, that will work for now.

**Comment by bradydean** [comment]
My goal here is to split the uri and extract a path segment. `SplitFilter` on `/` works, but a `UriSplitFilter` would be nice to see.

**Comment by RakhmedovRS** [comment]
@bradydean don't mind sharing your working config?

**Comment by bradydean** [comment]
@RakhmedovRS Unfortunately I don't have these configs anymore. We didn't end up using connect-file-pulse
