### ISSUE TITLE
Getting ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by DestroyerAlpha** [streamthoughts/kafka-connect-file-pulse#144]
I am trying to read a JSON Array.
Configuration for the source is as follows:
`{
   "connector.class":"io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
   "fs.listing.directory.path":"/tmp/connect-data/",
   "fs.listing.filters":"io.streamthoughts.kafka.connect.filepulse.fs.filter.RegexFileListFilter",
   "file.filter.regex.pattern":".*\\.json$",
   "task.reader.class":"io.streamthoughts.kafka.connect.filepulse.reader.BytesArrayInputReader",
   "offset.strategy":"name",
   "topic":"tracks-filepulse-json-01",
   "internal.kafka.reporter.bootstrap.servers":"broker:29092",
   "internal.kafka.reporter.topic":"connect-file-pulse-status",
   "fs.cleanup.policy.class":"io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy",
   "filters": "ParseJSON",
   "filters.ParseJSON.type":"io.streamthoughts.kafka.connect.filepulse.filter.JSONFilter",
   "filters.ParseJSON.merge":"true",
   "filters.ParseJSON.explode.array":"true",
   "tasks.max":1
}`

The JSON file that I am trying to parse is given in this [pastebin](https://pastebin.com/8Z0Sui0j)

I get the following error:
`ERROR [task-thread-jsonsource-0] Error while processing source file '[uri=file:/tmp/connect-data/tracks5.json, name='tracks5.json', contentLength=2158, lastModified=1623760023700, contentDigest=[digest=1632588054, algorithm='CRC32'], userDefinedMetadata={system.inode=125812, system.hostname=d1d6fc697d44}]' (io.streamthoughts.kafka.connect.filepulse.source.KafkaFileStateReporter)
io.streamthoughts.kafka.connect.filepulse.filter.FilterException: Error while reading json value, invalid JSON message.
        at io.streamthoughts.kafka.connect.filepulse.filter.JSONFilter.apply(JSONFilter.java:71)
        at io.streamthoughts.kafka.connect.filepulse.filter.AbstractMergeRecordFilter.apply(AbstractMergeRecordFilter.java:43)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline$FilterNode.apply(DefaultRecordFilterPipeline.java:159)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:131)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:99)
        at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:158)
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:125)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:289)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:256)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ArrayIndexOutOfBoundsException`

I can't figure out what the problem is. Could you please check?

**Comment by DestroyerAlpha** [comment]
The version that I am using is `streamthoughts/kafka-connect-file-pulse:2.0.0-RC1`

**Comment by fhussonnois** [comment]
Hi @DestroyerAlpha, my apologies for the late reply. I've failed to reproduce your issue using file-pulse 2.0.0 and the file you provided. Everything seems to be working as expected.

Below is the configuration which is compatible with the last FilePulse version : 

```
{
  "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
  "fs.listing.class" : "io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing",
  "fs.listing.directory.path": "/tmp/kafka-connect/examples",
  "fs.listing.filters": "io.streamthoughts.kafka.connect.filepulse.fs.filter.RegexFileListFilter",
  "file.filter.regex.pattern": ".*\\.json$",
  "tasks.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalBytesArrayInputReader",
  "offset.strategy": "name",
  "topic": "tracks-filepulse-json-01",
  "internal.kafka.reporter.bootstrap.servers": "broker:29092",
  "internal.kafka.reporter.topic": "connect-file-pulse-status",
  "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.fs.clean.LogCleanupPolicy",
  "filters": "ParseJSON,ExcludeFieldMessage",
  "filters.ParseJSON.type": "io.streamthoughts.kafka.connect.filepulse.filter.JSONFilter",
  "filters.ParseJSON.merge": "true",
  "filters.ParseJSON.explode.array": "true",
  "filters.ExcludeFieldMessage.type":"io.streamthoughts.kafka.connect.filepulse.filter.ExcludeFilter",
  "filters.ExcludeFieldMessage.fields":"message",
  "tasks.max": 1,
  "tasks.file.status.storage.bootstrap.servers": "broker:29092",
  "tasks.file.status.storage.topic": "connect-file-pulse-status",
  "tasks.file.status.storage.topic.partitions": 10,
  "tasks.file.status.storage.topic.replication.factor": 1
}
```
