### ISSUE TITLE
Removing special characters with AppendFilter from csv. 

### ISSUE THREAD

**Issue by kbegrow** [streamthoughts/kafka-connect-file-pulse#162]
Hello @fhussonnois,
I struggling a bit the the Append filter.
I am pretty sure I just do something wrong, since I haven’t used the Append filter til now. 
How can I actually removing characters (in this case double quotes) like in this simple csv: 
```
"Name","Age"
"Max","36"
...
```
So the first line is the header and than there will be 1-n lines. 
I would like to remove double quotes in header in values so I did a simple regex for each field.

Like this: 
````
    "filters.TransformFields1.type"   :"io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter",
    "filters.TransformFields1.field"  :"$.Name",
    "filters.TransformFields1.value"  :"{{ lowercase(replace_all(extract_array($.Name,0), '(\")', '')) }}",

    "filters.TransformFields2.type"   :"io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter",
    "filters.TransformFields2.field"  :"$.Age",
    "filters.TransformFields2.value"  :"{{ lowercase(replace_all(extract_array($.Age,0), '(\")', '')) }}",
````

I facing always following error for the fields:
````
io.streamthoughts.kafka.connect.filepulse.expression.accessor.AccessException: Cannot access to field 'Name'
	at io.streamthoughts.kafka.connect.filepulse.expression.accessor.TypedStructAccessor.read(TypedStructAccessor.java:60)
	at io.streamthoughts.kafka.connect.filepulse.expression.accessor.TypedStructAccessor.read(TypedStructAccessor.java:27)
	at io.streamthoughts.kafka.connect.filepulse.expression.PropertyExpression.evaluateReaders(PropertyExpression.java:188)
	at io.streamthoughts.kafka.connect.filepulse.expression.PropertyExpression.getValueForProperty(PropertyExpression.java:148)
	at io.streamthoughts.kafka.connect.filepulse.expression.PropertyExpression.readValue(PropertyExpression.java:86)
	at io.streamthoughts.kafka.connect.filepulse.expression.function.ExpressionArgument.evaluate(ExpressionArgument.java:42)
	at io.streamthoughts.kafka.connect.filepulse.expression.function.ExpressionArgument.evaluate(ExpressionArgument.java:26)
	at io.streamthoughts.kafka.connect.filepulse.expression.function.Arguments.evaluate(Arguments.java:121)
	at io.streamthoughts.kafka.connect.filepulse.expression.function.ExpressionFunctionExecutor.execute(ExpressionFunctionExecutor.java:55)
	at io.streamthoughts.kafka.connect.filepulse.expression.FunctionExpression.readValue(FunctionExpression.java:58)
	at io.streamthoughts.kafka.connect.filepulse.expression.function.ExpressionArgument.evaluate(ExpressionArgument.java:42)
	at io.streamthoughts.kafka.connect.filepulse.expression.function.ExpressionArgument.evaluate(ExpressionArgument.java:26)
	at io.streamthoughts.kafka.connect.filepulse.expression.function.Arguments.evaluate(Arguments.java:121)
	at io.streamthoughts.kafka.connect.filepulse.expression.function.ExpressionFunctionExecutor.execute(ExpressionFunctionExecutor.java:55)
	at io.streamthoughts.kafka.connect.filepulse.expression.FunctionExpression.readValue(FunctionExpression.java:58)
	at io.streamthoughts.kafka.connect.filepulse.expression.function.ExpressionArgument.evaluate(ExpressionArgument.java:42)
	at io.streamthoughts.kafka.connect.filepulse.expression.function.ExpressionArgument.evaluate(ExpressionArgument.java:26)
	at io.streamthoughts.kafka.connect.filepulse.expression.function.Arguments.evaluate(Arguments.java:121)
	at io.streamthoughts.kafka.connect.filepulse.expression.function.ExpressionFunctionExecutor.execute(ExpressionFunctionExecutor.java:55)
	at io.streamthoughts.kafka.connect.filepulse.expression.FunctionExpression.readValue(FunctionExpression.java:58)
	at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression$ReplacementExpression.readValue(SubstitutionExpression.java:199)
	at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression$ReplacementExpression.readValue(SubstitutionExpression.java:213)
	at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression.readValue(SubstitutionExpression.java:104)
	at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression.readValue(SubstitutionExpression.java:92)
	at io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter.apply(AppendFilter.java:87)
	at io.streamthoughts.kafka.connect.filepulse.filter.AbstractMergeRecordFilter.apply(AbstractMergeRecordFilter.java:43)
	at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline$FilterNode.apply(DefaultRecordFilterPipeline.java:159)
	at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:131)
	at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:99)
	at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:158)
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:127)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:273)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:240)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:182)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

````

Maybe anyone can help?

**Comment by fhussonnois** [comment]
Hi @kbegrow,

Can you share your complete configuration to better understand how you are processing your input file ? Also, I think it would be easiest to just cast the `Age`field into Integer instead of removing double-quotes ?

**Comment by kbegrow** [comment]
````
{
  "name": "test-customer-age-01",
  "config":{
    "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
    "key.converter":"io.confluent.connect.avro.AvroConverter",
    "key.converter.schema.registry.url":"http://scr.<url>.com:8081",
    "value.converter":"io.confluent.connect.avro.AvroConverter",
    "value.converter.schema.registry.url":"http://scr.<url>.com:8081",
    "task.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalRowFileInputReader",
    "fs.listing.class": "io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing",
    "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.fs.clean.LocalMoveCleanupPolicy",
    "fs.listing.filters": "io.streamthoughts.kafka.connect.filepulse.fs.filter.RegexFileListFilter",
    "fs.listing.directory.path": "/data/test/customers/",
    "fs.listing.interval.ms": "10000",
    "cleaner.output.failed.path": "/data/test/status/error/",
    "cleaner.output.succeed.path": "/data/test/status/processed/",
    "file.encoding" : "ASCII",
    "file.filter.regex.pattern": ".*\\.csv$",
    "skip.headers": "1",
    "topic": "test-customer-age",
    "tasks.file.status.storage.class": "io.streamthoughts.kafka.connect.filepulse.state.InMemoryFileObjectStateBackingStore",
    "tasks.file.status.storage.bootstrap.servers": "broker.<url>.com:9092",
    "tasks.file.status.storage.topic": "file-pulse-status",
    "offset.strategy": "name+hash",
    "tasks.max": "1",
    "filters"                            : "TransformFields1, TransformFields2, ParseLine,Rename1,Rename2",
    "filters.TransformFields1.type"   :"io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter",
    "filters.TransformFields1.field"  :"$.Name",
    "filters.TransformFields1.value"  :"{{ lowercase(replace_all(extract_array($.Name,0), '(\")', '')) }}",
    "filters.TransformFields2.type"   :"io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter",
    "filters.TransformFields2.field"  :"$.Age",
    "filters.TransformFields2.value"  :"{{ lowercase(replace_all(extract_array($.Alter,0), '(\")', '')) }}",
    "filters.ParseLine.type"             : "io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter",
    "filters.ParseLine.extractColumnName": "headers",
    "filters.ParseLine.trimColumn"       : "true",
    "filters.ParseLine.separator"        : ",",
    "filters.Rename1.type"          : "io.streamthoughts.kafka.connect.filepulse.filter.RenameFilter",
    "filters.Rename1.field"         : "Name",
    "filters.Rename1.target"        : "name",
    "filters.Rename2.type"          : "io.streamthoughts.kafka.connect.filepulse.filter.RenameFilter",
    "filters.Rename2.field"         : "Alter",
    "filters.Rename2.target"        : "age",
    "transforms": "castTypes",
    "transforms.castTypes.type" : "org.apache.kafka.connect.transforms.Cast$Value",
    "transforms.castTypes.spec" : "age:int32",
  }
}

````

**Comment by fhussonnois** [comment]
Hi @kbegrow, the `ParseLine` should be the first filter to be applied in the chain. 
So, you should try to change the `filters` property to : ` ParseLine,Rename1,Rename2,TransformFields1, TransformFields2` (order matters).

Note that if you rename data fields then make sure to also change the SCEL expression, i.e., `$.name` and `$.atler`

**Comment by kbegrow** [comment]
Hi @fhussonnois,

thank you for your help. I made it. :)
