### ISSUE TITLE
NoClassDefFoundError: io/streamthoughts/kafka/connect/filepulse/offset/OffsetManager

### ISSUE THREAD

**Issue by Vesli** [streamthoughts/kafka-connect-file-pulse#17]
Hello,

So after downloading and running `mvn clean install -DskipTests` I wanted to test your plugin locally following this configuration:

```
config/kafka-connect-file-pulse.conf
{
  "config": {
    "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
    "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy",
    "fs.scanner.class": "io.streamthoughts.kafka.connect.filepulse.scanner.local.LocalFSDirectoryWalker",
    "fs.scan.directory.path": "/Users/me/Documents/ingestion_test",
    "fs.scan.interval.ms": "10000",
    "internal.kafka.reporter.bootstrap.servers": "localhost:9092",
    "internal.kafka.reporter.id": "connect-file-pulse-quickstart-test",
    "internal.kafka.reporter.topic": "connect-file-pulse-status",
    "offset.strategy": "name+hash",
    "skip.headers": "1",
    "task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.BytesArrayInputReader",
    "topic": "ingestion",
    "tasks.max": 1
  },
  "name": "connect-file-pulse-quickstart-test"
}
```

alongside my local kafka.

Thus, on a naive and simple step I ran:
`bin/connect-standalone.sh config/connect-standalone.properties config/kafka-connect-file-pulse.conf`

but this returns the following error:

```
[2020-01-10 16:09:51,314] ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectStandalone:130)
java.lang.NoClassDefFoundError: io/streamthoughts/kafka/connect/filepulse/offset/OffsetManager
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.versionFor(DelegatingClassLoader.java:380)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.getPluginDesc(DelegatingClassLoader.java:350)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanPluginPath(DelegatingClassLoader.java:330)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanUrlsAndAddPlugins(DelegatingClassLoader.java:263)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.registerPlugin(DelegatingClassLoader.java:255)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initPluginLoader(DelegatingClassLoader.java:224)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initLoaders(DelegatingClassLoader.java:201)
	at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:60)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:79)
Caused by: java.lang.ClassNotFoundException: io.streamthoughts.kafka.connect.filepulse.offset.OffsetManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 13 more
```

on the folder for my plugin.path I put the 3 jar generated on the packaging (api, filters, plugin)

Am I doing something wrong? What would you suggest in order to run it with cli & without docker?

**Comment by fhussonnois** [comment]
Hi, you should try to run `mvn clean package -DskipTests`, then you can install the plug-in generated into connect-file-pulse-plugin/target/components/packages/streamthoughts-kafka-connect-file-pulse-1.3.0-SNAPSHOT.zip

The generated component follows the Confluent specifications, so you can installed it using `confluent-hub`.
