### ISSUE TITLE
LocalFSDirectoryListing input/output error on directories with large file counts

### ISSUE THREAD

**Issue by an0nz** [streamthoughts/kafka-connect-file-pulse#196]
### Overview
I have been testing file-pulse 2.4 as an option to process XML Call Detail Records (CDR's) for a number of voice servers, where each server produces around 350,000 files per day.

As the number of files in the source directory increase, file-pulse takes longer and longer to scan the directory before processing files. When the source directory has 70,000 or more files in it and I/O error is returned and file-pulse throws an exception.

### Test Setup

- Ubuntu 20.04
- 3 CPU, 3GB RAM, SSD storage
- Docker
- cp-kafka-connect-base docker container running file-pulse 2.4.0 from confluent hub
- Volume mount of /cdr into the container for XML CDR's
- File-Pulse general settings
`"fs.listing.class"                                     : "io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing",
                "fs.listing.filters"                                   : "io.streamthoughts.kafka.connect.filepulse.fs.filter.RegexFileListFilter",
                "fs.listing.directory.path"                            : "/cdr/pending/",
                "fs.scan.interval.ms"                                  : "2000",
                "tasks.reader.class"                                   : "io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalXMLFileInputReader",
                "file.filter.regex.pattern"                            : ".*\\.xml",
                "offset.strategy"                                      : "name",
                "reader.xpath.expression"                              : "/*/variables",
                "topic"                                                : "cdr_raw",
                "fs.cleanup.policy.class"                              : "io.streamthoughts.kafka.connect.filepulse.fs.clean.LocalMoveCleanupPolicy",
                "cleaner.output.failed.path"                           : "/cdr/failed/",
                "cleaner.output.succeed.path"                          : "/cdr/processed/",
                "tasks.max"                                            : 50,
                "max.scheduled.files"                                  : 5000,`

### Details
Under stress testing it is stably handling up to 7000 files a minute and can keep up with file generation, beyond this and it quickly falls behind until it falls over entirely with an error.

When the source directory has over 20,000 files in it, processing slows down considerably as on each run getting a list of files to process takes longer and longer regardless of what max.scheduled.files is set to.

If there are 70,000 files or more in the directory the below Input/output error occurs (It works with 69,000 files)
This is a problem in that this only allows for a few hours of file-pulse to be down during peak calling hours before it is unable to process the backlog of files without manual intervention to reduce the file count.

To see if the cause was in relation to file.filter.regex.pattern I tested without this setting and the same error occurred.
I have only tested on the one system so the limit at which the error occurs may be slightly different on other setups.

### Possible Cause
As far as I can tell (With my very limited java knowledge) the main reason for this issue relates to the DirectoryStream foreach loop not stopping when it reaches max.scheduled.files, and the max being enforced elsewhere as a global setting no matter which class you are using. 
https://github.com/streamthoughts/kafka-connect-file-pulse/blob/917ef7bd1c4117005e3fedbff5add98c798a504b/connect-file-pulse-filesystems/filepulse-local-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/fs/LocalFSDirectoryListing.java#L129

I am not certain this is the cause as the same error is thrown for all directories including the LocalMoveCleanupPolicy directories, it just seems the most likely cause as it happens when trying to list files for processing.

### Possible solution
Maybe this could be resolved by breaking the stream.forEach loop when it reaches max.scheduled.files

### Error
`xml-00","task":49}],"type":"source"}[2021-11-02 20:49:18,311] ERROR [source-filepulse-xml-00|worker] Unexpected error while monitoring filesystem. (io.streamthoughts.kafka.connect.filepulse.source.FileSystemMonitorThread:83)
java.nio.file.DirectoryIteratorException: java.nio.file.FileSystemException: /cdr/pending: Input/output error
        at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:169)
        at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.hasNext(UnixDirectoryStream.java:198)
        at java.base/java.lang.Iterable.forEach(Iterable.java:74)
        at io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing.listEligibleFiles(LocalFSDirectoryListing.java:129)
        at io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing.listObjects(LocalFSDirectoryListing.java:89)
        at io.streamthoughts.kafka.connect.filepulse.fs.DefaultFileSystemMonitor.updateFiles(DefaultFileSystemMonitor.java:283)
        at io.streamthoughts.kafka.connect.filepulse.fs.DefaultFileSystemMonitor.invoke(DefaultFileSystemMonitor.java:221)
        at io.streamthoughts.kafka.connect.filepulse.source.FileSystemMonitorThread.run(FileSystemMonitorThread.java:77)
Caused by: java.nio.file.FileSystemException: /cdr/pending: Input/output error
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.asIOException(UnixException.java:120)
        at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:168)
        ... 7 more
[2021-11-02 20:49:18,311] ERROR [source-filepulse-xml-00|worker] WorkerConnector{id=source-filepulse-xml-00} Connector raised an error (org.apache.kafka.connect.runtime.WorkerConnector:506)
java.nio.file.DirectoryIteratorException: java.nio.file.FileSystemException: /cdr/pending: Input/output error
        at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:169)
        at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.hasNext(UnixDirectoryStream.java:198)
        at java.base/java.lang.Iterable.forEach(Iterable.java:74)
        at io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing.listEligibleFiles(LocalFSDirectoryListing.java:129)
        at io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing.listObjects(LocalFSDirectoryListing.java:89)
        at io.streamthoughts.kafka.connect.filepulse.fs.DefaultFileSystemMonitor.updateFiles(DefaultFileSystemMonitor.java:283)
        at io.streamthoughts.kafka.connect.filepulse.fs.DefaultFileSystemMonitor.invoke(DefaultFileSystemMonitor.java:221)
        at io.streamthoughts.kafka.connect.filepulse.source.FileSystemMonitorThread.run(FileSystemMonitorThread.java:77)
Caused by: java.nio.file.FileSystemException: /cdr/pending: Input/output error
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.asIOException(UnixException.java:120)
        at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:168)
        ... 7 more
[2021-11-02 20:49:18,313] INFO [source-filepulse-xml-00|worker] Closing FileSystemMonitor resources (io.streamthoughts.kafka.connect.filepulse.fs.DefaultFileSystemMonitor:439)
[2021-11-02 20:49:18,313] INFO [source-filepulse-xml-00|worker] Closed FileSystemMonitor resources (io.streamthoughts.kafka.connect.filepulse.fs.DefaultFileSystemMonitor:442)
[2021-11-02 20:49:18,313] INFO [source-filepulse-xml-00|worker] Stopped filesystem monitoring thread. (io.streamthoughts.kafka.connect.filepulse.source.FileSystemMonitorThread:101)
[2021-11-02 20:49:18,314] INFO [source-filepulse-xml-00|worker] Uncaught error from file system monitoring thread [FileSystemMonitorThread] (io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector:130)
java.nio.file.DirectoryIteratorException: java.nio.file.FileSystemException: /cdr/pending: Input/output error
        at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:169)
        at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.hasNext(UnixDirectoryStream.java:198)
        at java.base/java.lang.Iterable.forEach(Iterable.java:74)
        at io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing.listEligibleFiles(LocalFSDirectoryListing.java:129)
        at io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing.listObjects(LocalFSDirectoryListing.java:89)
        at io.streamthoughts.kafka.connect.filepulse.fs.DefaultFileSystemMonitor.updateFiles(DefaultFileSystemMonitor.java:283)
        at io.streamthoughts.kafka.connect.filepulse.fs.DefaultFileSystemMonitor.invoke(DefaultFileSystemMonitor.java:221)
        at io.streamthoughts.kafka.connect.filepulse.source.FileSystemMonitorThread.run(FileSystemMonitorThread.java:77)
Caused by: java.nio.file.FileSystemException: /cdr/pending: Input/output error
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.asIOException(UnixException.java:120)
        at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:168)
        ... 7 more
[2021-11-02 20:49:18,314] ERROR [source-filepulse-xml-00|worker] WorkerConnector{id=source-filepulse-xml-00} Connector raised an error (org.apache.kafka.connect.runtime.WorkerConnector:506)
org.apache.kafka.connect.errors.ConnectException: Unexpected error from FileSystemMonitorThread
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector.lambda$start$0(FilePulseSourceConnector.java:131)
        at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2002)
Caused by: java.nio.file.DirectoryIteratorException: java.nio.file.FileSystemException: /cdr/pending: Input/output error
        at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:169)
        at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.hasNext(UnixDirectoryStream.java:198)
        at java.base/java.lang.Iterable.forEach(Iterable.java:74)
        at io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing.listEligibleFiles(LocalFSDirectoryListing.java:129)
        at io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing.listObjects(LocalFSDirectoryListing.java:89)
        at io.streamthoughts.kafka.connect.filepulse.fs.DefaultFileSystemMonitor.updateFiles(DefaultFileSystemMonitor.java:283)
        at io.streamthoughts.kafka.connect.filepulse.fs.DefaultFileSystemMonitor.invoke(DefaultFileSystemMonitor.java:221)
        at io.streamthoughts.kafka.connect.filepulse.source.FileSystemMonitorThread.run(FileSystemMonitorThread.java:77)
Caused by: java.nio.file.FileSystemException: /cdr/pending: Input/output error
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.asIOException(UnixException.java:120)
        at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:168)
        ... 7 more`

**Comment by fhussonnois** [comment]
Hi @an0nz, thank you very much for opening this issue.

I'm not very sure if that exception is due to the connector. Usually, a `java.nio.file.FileSystemException: *******: Input/output error` indicates a problem in storage, e.g. no space left, too many open files in system

Could you check the syslog and dmesg to see if the Linux kernel is reporting any underlying problems with your disk ?

**Comment by an0nz** [comment]
Hi @fhussonnois, there are no errors in dmesg or syslog, this is not a production setup in that it is a docker container in a HyperV VM on Windows 10 so it is possible something else is going on, the slowly degrading performance as the file count increased seemed to fit the way the max.scheduled.files logic was implemented but you may be correct in regards to the issue when hitting 70k files.

I will try load all the files onto one of our staging docker servers to see if I can hit the same issue there and will report back.

**Comment by an0nz** [comment]
Thanks for the response @fhussonnois, after running it up on an Ubuntu 20.04 server in our VMware cluster with the same volume mount setup I tested out to 450,000 files without issue and they processed much faster.
Must have been something to do with the VM running on my machine.
