### ISSUE TITLE
ERROR Failed to initialized a new iterator for object file

### ISSUE THREAD

**Issue by kbegrow** [streamthoughts/kafka-connect-file-pulse#198]
Hi @fhussonnois 

I'm facing an issue with a pretty simple csv file which is encoded as utf-8.
I wonder where this comes from, the file is definitely encoded in utf-8:
```
file -i test-cams-2021-11-15-16-32.csv
test-cams-2021-11-15-16-32.csv: text/plain; charset=utf-8
```
Error:
```
[2021-11-15 16:32:56,814] INFO Opening new iterator for: file:/data/import_flatfiles/customer/test/import/test-cams-2021-11-15-16-32.csv (io.streamthoughts.kafka.connect.filepulse.source.DelegateFileInputIterator)
[2021-11-15 16:32:56,828] ERROR Failed to initialized a new iterator for object file 'file:/data/import_flatfiles/customer/test/import/test-cams-2021-11-15-16-32.csv'. (io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer)
	at io.streamthoughts.kafka.connect.filepulse.fs.reader.text.RowFileInputIteratorConfig.charset(RowFileInputIteratorConfig.java:73)
	at io.streamthoughts.kafka.connect.filepulse.fs.reader.text.RowFileInputIteratorFactory.newIterator(RowFileInputIteratorFactory.java:64)
	at io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalRowFileInputReader.newIterator(LocalRowFileInputReader.java:61)
	at io.streamthoughts.kafka.connect.filepulse.fs.reader.AbstractFileInputReader.newIterator(AbstractFileInputReader.java:48)
	at io.streamthoughts.kafka.connect.filepulse.source.DelegateFileInputIterator.open(DelegateFileInputIterator.java:85)
	at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.openAndGetIteratorOrNullIfInvalid(DefaultFileRecordsPollingConsumer.java:325)
	at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:173)
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:177)
[2021-11-15 16:32:56,828] ERROR Error while processing source file '[uri=file:/data/import_flatfiles/customer/test/import/test-cams-2021-11-15-16-32.csv, name='test-cams-2021-11-15-16-32.csv', contentLength=1937, lastModified=1636990370226, contentDigest=[digest=2453840474, algorithm='CRC32'], userDefinedMetadata={system.inode=-4611621971875069952, system.hostname=StagingKmb000002}]' (io.streamthoughts.kafka.connect.filepulse.source.KafkaFileStateReporter)
	at io.streamthoughts.kafka.connect.filepulse.fs.reader.text.RowFileInputIteratorConfig.charset(RowFileInputIteratorConfig.java:73)
	at io.streamthoughts.kafka.connect.filepulse.fs.reader.text.RowFileInputIteratorFactory.newIterator(RowFileInputIteratorFactory.java:64)
	at io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalRowFileInputReader.newIterator(LocalRowFileInputReader.java:61)
	at io.streamthoughts.kafka.connect.filepulse.fs.reader.AbstractFileInputReader.newIterator(AbstractFileInputReader.java:48)
	at io.streamthoughts.kafka.connect.filepulse.source.DelegateFileInputIterator.open(DelegateFileInputIterator.java:85)
	at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.openAndGetIteratorOrNullIfInvalid(DefaultFileRecordsPollingConsumer.java:325)
	at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:173)
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:177)
[2021-11-15 16:32:56,828] INFO Completed all object files. FilePulse source task is transitioning to IDLE state while waiting for new reconfiguration request from source connector. (io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask)
[2021-11-15 16:32:56,828] INFO Closing resources FilePulse source task (io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask)

```

CSV:
```
date;cam1 (In);cam1 (Out);cam2 (In);cam2 (Out)
2021-11-15 00:00:00;0;0;0;0
2021-11-15 00:15:00;0;0;0;0
2021-11-15 00:30:00;0;0;0;0
2021-11-15 00:45:00;0;0;0;0
2021-11-15 01:00:00;0;0;0;0
2021-11-15 01:15:00;0;0;0;0
```

The connector is configured with encoding UTF_8
Connector Version is 2.2.0

Do you have any idea?

**Comment by kbegrow** [comment]
found the reason. ticket is closed
