### ISSUE TITLE
Error creating Connector: Failed to transition connector FilePulseMain to state STARTED

### ISSUE THREAD

**Issue by dmarupov** [streamthoughts/kafka-connect-file-pulse#212]
I am getting the following error when I try to create a File Pulse connector:

```
org.sourcelab.kafka.connect.apiclient.rest.exceptions.InvalidRequestException: Failed to transition connector FilePulseMain to state STARTED
	at org.sourcelab.kafka.connect.apiclient.rest.exceptions.InvalidRequestException.factory(InvalidRequestException.java:74)
	at org.sourcelab.kafka.connect.apiclient.KafkaConnectClient.submitRequest(KafkaConnectClient.java:398)
	at org.sourcelab.kafka.connect.apiclient.KafkaConnectClient.addConnector(KafkaConnectClient.java:238)
	at io.conduktor.connect.service.KafkaConnectService$createConnector$2.invokeSuspend(KafkaConnectService.kt:160)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

I am using FilePulse version 2.4.1
Java version: openjdk version "11.0.13"
My connector configurations are as follows:
```
{
  "name" : "FilePulseMain",
  "config" : {
    "connector.class" : "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
    "filters" : "Drop",
    "filters.Drop.if" : "{{ matches($.root.data, '(Hi|Hello|World)') }}",
    "filters.Drop.invert" : "true",
    "filters.Drop.type" : "io.streamthoughts.kafka.connect.filepulse.filter.DropFilter",
    "filters.Exclude.fields" : "message",
    "filters.Exclude.type" : "io.streamthoughts.kafka.connect.filepulse.filter.ExcludeFilter",
    "filters.JsonFilter.source" : "message",
    "filters.JsonFilter.target" : "payload",
    "filters.JsonFilter.type" : "io.streamthoughts.kafka.connect.filepulse.filter.JSONFilter",
    "fs.cleanup.policy.class" : "io.streamthoughts.kafka.connect.filepulse.fs.clean.LogCleanupPolicy",
    "fs.listing.class" : "io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing",
    "fs.scan.directory.path" : "/my/filepath",
    "header.converter" : "org.apache.kafka.connect.storage.StringConverter",
    "internal.kafka.reporter.bootstrap.servers" : "mylocalhost:9092",
    "key.converter" : "org.apache.kafka.connect.storage.StringConverter",
    "name" : "FilePulseMain",
    "offset.strategy" : "name",
    "read.max.wait.ms" : "120000",
    "tasks.reader.class" : "io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalRowFileInputReader",
    "topic" : "kafka-topic",
    "value.converter" : "org.apache.kafka.connect.json.JsonConverter"
  }
}
```

I had similar configuration with FilePulse version 1.6.
With the newer version of FilePulse, I wonder if I am missing something. I would appreciate any guidance on this to solve this issue.

Thank you in advance.

**Comment by fhussonnois** [comment]
Hi @dmarupov,

Some connector's config properties has changed since 2.x version.

* Replace `internal.kafka.reporter.bootstrap.servers` with  `tasks.file.status.storage.bootstrap.servers`
* Replace `offset.strategy` with `offset.attributes.string`

This should be OK after that.

**Comment by dmarupov** [comment]
Hi @fhussonnois,

The suggestion you made fix the issue for us. So this has been resolved.

Thank you again for your prompt response.
