### ISSUE TITLE
java.nio.file.FileSystemNotFoundException: Provider "gcs" not installed

### ISSUE THREAD

**Issue by lucas-dclrcq** [streamthoughts/kafka-connect-file-pulse#217]
Hello,

I'm trying to configure the file pulse connector to watch files on a Google Cloud Storage Bucket, but the connector fails on startup with the following error :

```bash
[2022-01-14 15:26:48,037] ERROR WorkerSourceTask{id=test-ecollect-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
java.nio.file.FileSystemNotFoundException: Provider "gcs" not installed
	at java.base/java.nio.file.Path.of(Path.java:212)
	at java.base/java.nio.file.Paths.get(Paths.java:97)
	at io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalFileStorage.exists(LocalFileStorage.java:59)
	at io.streamthoughts.kafka.connect.filepulse.reader.StorageAwareFileInputReader.canBeRead(StorageAwareFileInputReader.java:41)
	at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.addAll(DefaultFileRecordsPollingConsumer.java:86)
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:159)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:304)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:248)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
	
Here is the configuration I'm using : 

```json
{
  "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
  "fs.listing.class": "io.streamthoughts.kafka.connect.filepulse.fs.GcsFileSystemListing",
  "fs.listing.directory.path":"/",
  "fs.listing.interval.ms": "10000",
  "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.fs.clean.LogCleanupPolicy",
  "gcs.credentials.json": "<CREDENTIALS>",
  "gcs.bucket.name": "<bucketname>",
  "file.filter.regex.pattern":".*\\.csv$",
  "offset.attributes.string": "name+hash",
  "skip.headers": "1",
  "topic": "<TOPICNAME>",
  "tasks.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalRowFileInputReader",
  "tasks.file.status.storage.class": "io.streamthoughts.kafka.connect.filepulse.state.KafkaFileObjectStateBackingStore",
  "tasks.file.status.storage.bootstrap.servers": "<BOOTSTRAPSERVERS>",
  "tasks.file.status.storage.sasl.jaas.config": "<JAASCONFIG>",
  "tasks.file.status.storage.group.id": "group",
  "tasks.file.status.storage.security.protocol": "SASL_SSL",
  "tasks.file.status.storage.sasl.mechanism": "PLAIN",
  "tasks.file.status.storage.consumer.sasl.jaas.config": "<JAASCONFIG>",
  "tasks.file.status.storage.consumer.group.id": "group",
  "tasks.file.status.storage.consumer.security.protocol": "SASL_SSL",
  "tasks.file.status.storage.consumer.sasl.mechanism": "PLAIN",
  "tasks.file.status.storage.producer.sasl.jaas.config": "<JAASCONFIG>",
  "tasks.file.status.storage.producer.group.id": "group",
  "tasks.file.status.storage.producer.security.protocol": "SASL_SSL",
  "tasks.file.status.storage.producer.sasl.mechanism": "PLAIN",
  "tasks.file.status.storage.topic": "<STORAGETOPIC>",
  "tasks.file.status.storage.topic.partitions": 4,
  "tasks.file.status.storage.topic.replication.factor": 3,
  "tasks.max": 1
}
```

Any idea on what I'm doing wrong ?

Best regards,

Lucas

**Comment by fhussonnois** [comment]
Hi @lucas-dclrcq, you have configured your connector to use the :
```
 "tasks.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalRowFileInputReader"
```

When using the `GcsFileSystemListing` you should also use a corresponding reader : 
```
 "tasks.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.reader.GcsRowFileInputReader"
```
Here is the documentation: https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/file-readers/

Hope this will help :)

Florian.

**Comment by lucas-dclrcq** [comment]
Yes this helped, thank you !
