### ISSUE TITLE
NullPointerException on AWS credentials

### ISSUE THREAD

**Issue by mdimas** [streamthoughts/kafka-connect-file-pulse#219]
Hi,

I'm trying to use the `InstanceProfileCredentialsProvider` for the `aws.credentials.provider.class`, so I'm not setting `aws.access.key.id` or `aws.secret.access.key`. That seems to be resulting in a NullPointerException.

```
[2022-02-01 00:06:15,004] ERROR WorkerConnector{id=***} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector)
java.lang.NullPointerException
	at io.streamthoughts.kafka.connect.filepulse.fs.AmazonS3ClientUtils.newCredentialsProvider(AmazonS3ClientUtils.java:84)
	at io.streamthoughts.kafka.connect.filepulse.fs.AmazonS3ClientUtils.createS3Client(AmazonS3ClientUtils.java:69)
	at io.streamthoughts.kafka.connect.filepulse.fs.AmazonS3FileSystemListing.configure(AmazonS3FileSystemListing.java:64)
	at io.streamthoughts.kafka.connect.filepulse.fs.AmazonS3FileSystemListing.configure(AmazonS3FileSystemListing.java:58)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:401)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:430)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:415)
	at io.streamthoughts.kafka.connect.filepulse.config.CommonSourceConfig.getFileSystemListing(CommonSourceConfig.java:225)
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector.start(FilePulseSourceConnector.java:115)
```

**Comment by fhussonnois** [comment]
Hi @mdimas, thank you for reporting this issue. You can try the fix using this image:
```
$ docker pull streamthoughts/kafka-connect-file-pulse:master
```

**Comment by mdimas** [comment]
Hi @fhussonnois, thanks for the quick response. That image is working for me when using the `InstanceProfileCredentialsProvider`.
