### ISSUE TITLE
Unable to process JSON with fields that have a nested field with the same name

### ISSUE THREAD

**Issue by kurtis-ley** [streamthoughts/kafka-connect-file-pulse#240]
**Context**

I'm using FilePulse to pick up JSON files from a GCS bucket being published by a proprietary vendor.
These files are published as arrays of JSON documents (around 15MB in size).
 I'm unable to manipulate the files before they are written to the bucket.

**Issue**

- I am using the JSONConverter to process these files
     -  I am unable to use the AvroConverter because some of the documents have numerical keys ("100", "115") and Avro doesn't like field names that start with numbers
- I am using the JSONFilter to first parse the ByteArray
- Then I'm using ExplodeFilter to explode the array into separate documents 
     - I am unable to explode within the JSONFilter because the schemas are not consistent between documents and it fails trying to merge schemas
- Some files cannot be processed and it fails on CyclicSchemaWrapper.name
- The failure does not specify where the error occurs at, so I had to manually pick apart a 500K line JSON file until I found a single document it was unable to process
- This error occurs when a JSON document has a nested field with the same name

**JSON file that DOES NOT work:**
```
[
    {
    "tableName": "table",
    "fields": {
        "PrimaryID": "F507FD1E7EDE224ABF14A7D90AC886A7",
        "Data": {
            "created_at": "2022-04-01T19:03:17.550Z",
            "user_id": -3,
            "data": {
                "action": "Update",
                "record_data": {
                    "creation_date": "20220401",
                    "id": 1804820,
                },
                "record": {
                    "field_number": 28,
                    "primary_id": "4E7E37E5F2C4D942BFCE0CD67C3194D1",
                    "record_number": 49436,
                    "table_number": 74
                }
            }
        }
    },
    "primaryKey": "F507FD1E7EDE224ABF14A7D90AC886A7"
}
]
```

**JSON file that DOES work:**
```
[
    {
    "tableName": "table",
    "fields": {
        "PrimaryID": "F507FD1E7EDE224ABF14A7D90AC886A7",
        "Data": {
            "created_at": "2022-04-01T19:03:17.550Z",
            "user_id": -3,
            "nested_data": {
                "action": "Update",
                "record_data": {
                    "creation_date": "20220401",
                    "id": 1804820,
                },
                "record": {
                    "field_number": 28,
                    "primary_id": "4E7E37E5F2C4D942BFCE0CD67C3194D1",
                    "record_number": 49436,
                    "table_number": 74
                }
            }
        }
    },
    "primaryKey": "F507FD1E7EDE224ABF14A7D90AC886A7"
}
]
```
The only difference between these two JSON files is that I renamed the nested "data" key to "nested_data"

**FilePulse config:**
```
{
  "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
  "tasks.max": "1",
  "tasks.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.reader.GcsBytesArrayInputReader",
  "tasks.file.status.storage.topic": "__filepulse.status",
  "tasks.file.status.storage.class": "io.streamthoughts.kafka.connect.filepulse.state.KafkaFileObjectStateBackingStore",
  "fs.listing.class": "io.streamthoughts.kafka.connect.filepulse.fs.GcsFileSystemListing",
  "fs.listing.filters": "io.streamthoughts.kafka.connect.filepulse.fs.filter.RegexFileListFilter",
  "fs.listing.task.delegation.enabled": "false",
  "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.fs.clean.LogCleanupPolicy",
  "fs.cleanup.policy.triggered.on": "COMPLETED",
  "fs.listing.interval.ms": "5000",
  "max.scheduled.files": "1000",
  "gcs.bucket.name": "GCS_BUCKET",
  "gcs.blobs.filter.prefix": "",
  "file.filter.regex.pattern": ".*\\.json",
  "filters": "ParseJSONArray, ExplodeJSONArray",
  "filters.ParseJSONArray.type": "io.streamthoughts.kafka.connect.filepulse.filter.JSONFilter",
  "filters.ParseJSONArray.charset": "UTF-8",
  "filters.ParseJSONArray.source": "message",
  "filters.ParseJSONArray.explode.array": "false",
  "filters.ParseJSONArray.merge": "false",
  "filters.ExplodeJSONArray.type": "io.streamthoughts.kafka.connect.filepulse.filter.ExplodeFilter",
  "filters.ExplodeJSONArray.source": "message",
  "key.converter": "org.apache.kafka.connect.json.JsonConverter",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter"
  }
```

**Stack Trace:**
```
io.streamthoughts.kafka.connect.filepulse.errors.ConnectFilePulseException: Failed to convert data into connect record: 'gcs://GCSBUCKET/GCSFILE.json'
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.buildSourceRecord(FilePulseSourceTask.java:297)
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.lambda$poll$0(FilePulseSourceTask.java:205)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.LinkedList$ListItr.forEachRemaining(LinkedList.java:960)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:308)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:263)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.StackOverflowError
	at io.streamthoughts.kafka.connect.filepulse.schema.CyclicSchemaWrapper.name(CyclicSchemaWrapper.java:57)
	at io.streamthoughts.kafka.connect.filepulse.schema.CyclicSchemaWrapper.name(CyclicSchemaWrapper.java:57)
	at io.streamthoughts.kafka.connect.filepulse.schema.CyclicSchemaWrapper.name(CyclicSchemaWrapper.java:57)
	at io.streamthoughts.kafka.connect.filepulse.schema.CyclicSchemaWrapper.name(CyclicSchemaWrapper.java:57)
	at io.streamthoughts.kafka.connect.filepulse.schema.CyclicSchemaWrapper.name(CyclicSchemaWrapper.java:57)
	at io.streamthoughts.kafka.connect.filepulse.schema.CyclicSchemaWrapper.name(CyclicSchemaWrapper.java:57)
	at io.streamthoughts.kafka.connect.filepulse.schema.CyclicSchemaWrapper.name(CyclicSchemaWrapper.java:57)
...and this goes on for hundreds of lines
```

**Comment by fhussonnois** [comment]
Hi @kurtis-ley, thank you for reporting that issue. Could your tell me which FilePulse version are you using ?

**Comment by kurtis-ley** [comment]
Yep! Version 2.4.3. I'm pulling it from Confluent Hub.

**Comment by fhussonnois** [comment]
Hi @kurtis-ley, I have reproduced your error. Unfortunately, this issue is not trivial to fix. 
The connector attempts to merge schemas for fields having the same name record/struct name but currently its hard to determine if two fields are nested or not.

Right now, I suggest to you, if possible, to rename your second `data` field like in your example. You should be able to use the [`RenameFilter`](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters/#renamefilter) for doing that.

**Comment by kurtis-ley** [comment]
Will do, thank you!

**Comment by senadjukic** [comment]
I have the same issue with nested structures with repeating names with XML. Any plans to optimize this? I guess other libs have this edge solved for sure.
