### ISSUE TITLE
Error while starting connector

### ISSUE THREAD

**Issue by dmarupov** [streamthoughts/kafka-connect-file-pulse#26]
I am trying to get the File Pulse Connector started and I am getting the following error:

[2020-05-20 18:14:30,911] INFO ConnectorConfig values: 
        filters = []
        fs.cleanup.policy.class = class io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy
        fs.scan.directory.path = /mnt/kafkashared/
        fs.scan.filters = []
        fs.scan.interval.ms = 10000
        fs.scanner.class = class io.streamthoughts.kafka.connect.filepulse.scanner.local.LocalFSDirectoryWalker
        internal.kafka.reporter.bootstrap.servers = my.ip.address:9093,my.ip.address:9094,my.ip.address:9095
        internal.kafka.reporter.id = connect-distributed-cluster
        internal.kafka.reporter.topic = connect-distributed-status
        offset.strategy = name+hash
        task.reader.class = class io.streamthoughts.kafka.connect.filepulse.reader.RowFileInputReader
        topic = file-pulse-topic
 (io.streamthoughts.kafka.connect.filepulse.config.ConnectorConfig:347)
[2020-05-20 18:14:30,911] INFO Registering new store for name : connect-distributed-cluster (io.streamthoughts.kafka.connect.filepulse.state.StateBackingStoreRegistry:60)
[2020-05-20 18:14:30,912] INFO State store already registered for name : connect-distributed-cluster (io.streamthoughts.kafka.connect.filepulse.state.StateBackingStoreRegistry:64)
[2020-05-20 18:14:30,912] INFO Getting access on FileStateBackingStore instance for group connect-distributed-cluster (io.streamthoughts.kafka.connect.filepulse.state.StateBackingStoreRegistry:73)
[2020-05-20 18:14:30,912] INFO Added codec 'class io.streamthoughts.kafka.connect.filepulse.scanner.local.codec.ZipCodec' (io.streamthoughts.kafka.connect.filepulse.scanner.local.codec.CodecManager:48)
[2020-05-20 18:14:30,912] INFO Added codec 'class io.streamthoughts.kafka.connect.filepulse.scanner.local.codec.GZipCodec' (io.streamthoughts.kafka.connect.filepulse.scanner.local.codec.CodecManager:48)
[2020-05-20 18:14:30,912] INFO Added codec 'class io.streamthoughts.kafka.connect.filepulse.scanner.local.codec.TarballCodec' (io.streamthoughts.kafka.connect.filepulse.scanner.local.codec.CodecManager:48)
[2020-05-20 18:14:30,913] INFO Creating local filesystem scanner (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner:127)
[2020-05-20 18:14:30,913] ERROR WorkerConnector{id=file-pulse-connector} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector:119)
java.lang.IllegalStateException: Cannot init again.
        at io.streamthoughts.kafka.connect.filepulse.storage.KafkaStateBackingStore.start(KafkaStateBackingStore.java:94)
        at io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner.<init>(LocalFileSystemScanner.java:152)
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector.start(FilePulseSourceConnector.java:107)
        at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)
        at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)
        at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:196)
        at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:252)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1079)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1300(DistributedHerder.java:117)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$11.call(DistributedHerder.java:797)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$11.call(DistributedHerder.java:783)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:296)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:245)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2020-05-20 18:14:30,915] WARN Discarding state update value with invalid key : status-connector-file-pulse-connector (io.streamthoughts.kafka.connect.filepulse.storage.KafkaStateBackingStore:285)
[2020-05-20 18:14:30,919] INFO Finished creating connector file-pulse-connector (org.apache.kafka.connect.runtime.Worker:268)
[2020-05-20 18:14:30,919] INFO [Worker clientId=connect-1, groupId=connect-distributed-cluster] Skipping reconfiguration of connector file-pulse-connector since it is not running (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1155)

I am not sure what the error is. I am having a difficulty pinpointing the issue.
Could there be something wrong with my configuration?
Thank you.

**Comment by dmarupov** [comment]
I was able to solve this issue by replacing my internal.kafka.reporter.topic from "connect-distributed-status" to "connect-file-pulse-status".  The topic: "connect-distributed-status" is what I had created for my default Kafka Connect. Not sure if internal.kafka.reporter.topic needs to be its own topic?

**Comment by fhussonnois** [comment]
@dmarupov the connector uses its own internal topic for reptoring issue so you should never configure the `internal.kafka.reporter.topic` with the status topic used by your Connect Worker

**Comment by fhussonnois** [comment]
Also, regarding your first message this actually a known issue. 

The connector initializes a singleton in the JVM (`KafkaStateBackingStore`) per `internal.kafka.reporter.id` to track the progression of each file. When the connector is stopped properly the `KafkaStateBackingStore` is closed.

However, if you don't succed to start the connector at first and the connector crashes abruptly then you will have memory leak. The connector will try to restart the previous `KafkaStateBackingStore`.

This should not happen in production. To solve that problem during development you have to restart your Kafka Worker or change the `internal.kafka.reporter.id` property.

Please, could you close this issue if your problem is resolved. Thank you.

**Comment by dmarupov** [comment]
Thank you for the clarification.
