### ISSUE TITLE
Using DateFilter with pattern yyy-MM-dd

### ISSUE THREAD

**Issue by bertrandcedric** [streamthoughts/kafka-connect-file-pulse#277]
When I try to use the DateFilter with the pattern yyy-MM-dd and the value 2001-01-01, I got the following error :

`
Caused by: java.time.DateTimeException: Unable to obtain Instant from TemporalAccessor: {},ISO,Z resolved to 2001-01-01 of type java.time.format.Parsed
	at java.base/java.time.Instant.from(Instant.java:380)
	at io.streamthoughts.kafka.connect.filepulse.filter.DateFilter.apply(DateFilter.java:115)
	... 29 more
Caused by: java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: InstantSeconds
	at java.base/java.time.format.Parsed.getLong(Parsed.java:209)
	at java.base/java.time.Instant.from(Instant.java:375)
	... 30 more
`

Is there a solution to parse only a date (day, month, year) with this filter or is it only for a full timestamp ?

Thanks

**Comment by fhussonnois** [comment]
Hi @bertrandcedric, this is an issue of the `DateFilter`.  You should be able to use the `AppendFilter` with the `to_timestamp` expression function. e.g. `{{ to_timestamp($value.YOUR_DATE_FIELD, 'yyy-MM-dd') }}`
