### ISSUE TITLE
`CSVFilter`: `io.streamthoughts.kafka.connect.filepulse.data.DataException: fieldName cannot be null.`

### ISSUE THREAD

**Issue by bradydean** [streamthoughts/kafka-connect-file-pulse#285]
**Describe the bug**

This exception occurs when processing a CSV file using the new `CSVFilter`.

I think the issue has something to do with `filters.csv.extractColumnName`. Without setting this option the file is processed.

```
connect-file-pulse                  | io.streamthoughts.kafka.connect.filepulse.data.DataException: fieldName cannot be null.
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.data.StructSchema.field(StructSchema.java:83)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.filter.AbstractDelimitedRowFilter.lambda$inferSchemaFromRecord$2(AbstractDelimitedRowFilter.java:157)
connect-file-pulse                  | 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.filter.AbstractDelimitedRowFilter.inferSchemaFromRecord(AbstractDelimitedRowFilter.java:157)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.filter.AbstractDelimitedRowFilter.apply(AbstractDelimitedRowFilter.java:117)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline$FilterNode.apply(DefaultRecordFilterPipeline.java:162)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:134)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:102)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:176)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:199)
connect-file-pulse                  | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:296)
connect-file-pulse                  | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:253)
connect-file-pulse                  | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
connect-file-pulse                  | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:237)
connect-file-pulse                  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
connect-file-pulse                  | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
connect-file-pulse                  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
connect-file-pulse                  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
connect-file-pulse                  | 	at java.base/java.lang.Thread.run(Thread.java:829)
connect-file-pulse                  | 2022-06-01 17:59:12,857 ERROR [task-thread-csv-test-0] Caught unexpected error while processing file. Ignore and continue (io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask)
connect-file-pulse                  | io.streamthoughts.kafka.connect.filepulse.data.DataException: fieldName cannot be null.
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.data.StructSchema.field(StructSchema.java:83)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.filter.AbstractDelimitedRowFilter.lambda$inferSchemaFromRecord$2(AbstractDelimitedRowFilter.java:157)
connect-file-pulse                  | 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.filter.AbstractDelimitedRowFilter.inferSchemaFromRecord(AbstractDelimitedRowFilter.java:157)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.filter.AbstractDelimitedRowFilter.apply(AbstractDelimitedRowFilter.java:117)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline$FilterNode.apply(DefaultRecordFilterPipeline.java:162)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:134)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:102)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:176)
connect-file-pulse                  | 	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:199)
connect-file-pulse                  | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:296)
connect-file-pulse                  | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:253)
connect-file-pulse                  | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
connect-file-pulse                  | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:237)
connect-file-pulse                  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
connect-file-pulse                  | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
connect-file-pulse                  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
connect-file-pulse                  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
connect-file-pulse                  | 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**To Reproduce**

This is my connector config

```
{
    "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
    "topic": "test.csv",
    "tasks.max": "1",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "tasks.file.status.storage.bootstrap.servers": "kafka:9092",
    "fs.listing.class": "io.streamthoughts.kafka.connect.filepulse.fs.AmazonS3FileSystemListing",
    "fs.listing.internal.ms": "10000",
    "file.filter.regex.pattern": ".*\\.csv$",
    "tasks.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.reader.AmazonS3RowFileInputReader",
    "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.fs.clean.DeleteCleanupPolicy",
    "skip.headers": "1",
    "aws.s3.region": "us-east-2",
    "aws.s3.bucket.name": "test",
    "aws.credentials.provider.class": "com.amazonaws.auth.DefaultAWSCredentialsProviderChain",
    "filters": "csv",
    "filters.csv.type": "io.streamthoughts.kafka.connect.filepulse.filter.CSVFilter",
    "filters.csv.separator": ",",
    "filters.csv.ignore.quotations": "false",
    "filters.csv.ignore.leading.whitespace": "true",
    "filters.csv.quote.char": "\"",
    "filters.csv.strict.quotes": "true",
    "filters.csv.extractColumnName": "headers",
    "filters.csv.trimColumn": "true"
}
```

**Expected behavior**
File should be parsed and message created with keys from the header row.

**Additional context**

I'm working on the latest `master` docker container, diget `ed4958f594d8`

**Comment by bradydean** [comment]
Looks like I misunderstood what `filters.csv.strict.quotes` does. Turning that off fixed the issue. It was returning empty strings for the column names leading to the exception thrown.

**Comment by bradydean** [comment]
https://github.com/bradydean/kafka-connect-file-pulse/tree/285-test

Here I have a test case to reproduce.
