### ISSUE TITLE
CSVfilter 

### ISSUE THREAD

**Issue by audirline** [streamthoughts/kafka-connect-file-pulse#378]
Hello,

First of all, thank you for this great connector. It helps me a lot ingesting files into Kafka topics.
I have some issues with the CsvFilter Filter.
What I would like to achieve is the following.

I'd like to ingest the data from a CSV file into my kafka topic. So i was thinking about using the LocalBytesArrayInputReader reader in order to put the entire csv file into a message in a kafka topic. Then use the processingfilter CsvFilter https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters/#csvfilter in order to decode the byte in the kafka topic.

Here is below my connector properties:

```
name=connect-file-pulse-csv
connector.class=io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector
topic=harfang-csv2
tasks.max=1
fs.scan.directory.path=/tutorial/source/demo-1/filepulse
fs.scan.filters=io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter
file.filter.regex.pattern=.*\\.csv$
tasks.reader.class=io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalRowFileInputReader
offset.strategy=name
skip.headers=1
fs.cleanup.policy.class=io.streamthoughts.kafka.connect.filepulse.fs.clean.LogCleanupPolicy
fs.listing.class=io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing
tasks.file.status.storage.bootstrap.servers=localhost:9092
fs.listing.directory.path=/tutorial/source/demo-1/filepulse
filters=ParseCSVLine
filters.ParseCSVLine.type=io.streamthoughts.kafka.connect.filepulse.filter.CSVFilter
filters.ParseCSVLine.extract.column.name=headers
filters.ParseCSVLine.separator=;
filters.ParseCSVLine.trim.column=true
```

But when starting the connector i have the errors in the logs:

```
[2023-02-06 02:52:23,981] INFO EnrichedConnectorConfig values:

        [connect.schema.keep.leading.underscores.on.record.name](http://connect.schema.keep.leading.underscores.on.record.name/) = false

        file.uris.provider = class io.streamthoughts.kafka.connect.filepulse.fs.DefaultTaskFileURIProvider

        filters = [ParseCSVLine]

        filters.ParseCSVLine.auto.generate.column.names = true

        filters.ParseCSVLine.autoGenerateColumnNames = null

        filters.ParseCSVLine.columns = null

        filters.ParseCSVLine.duplicate.columns.as.array = false

        filters.ParseCSVLine.duplicateColumnsAsArray = null

        filters.ParseCSVLine.escape.char = \

        [filters.ParseCSVLine.extract.column.name](http://filters.parsecsvline.extract.column.name/) = headers

        filters.ParseCSVLine.extractColumnName = null

        filters.ParseCSVLine.if = null

        filters.ParseCSVLine.ignore.leading.whitespace = true

        filters.ParseCSVLine.ignore.quotations = false

        filters.ParseCSVLine.ignoreFailure = false

        filters.ParseCSVLine.invert = false

        filters.ParseCSVLine.quote.char = "

        filters.ParseCSVLine.separator = ;

        filters.ParseCSVLine.strict.quotes = false

        filters.ParseCSVLine.trim.column = true

        filters.ParseCSVLine.trimColumn = null

        filters.ParseCSVLine.type = class io.streamthoughts.kafka.connect.filepulse.filter.CSVFilter

        filters.ParseCSVLine.withOnFailure = null

        fs.listing.class = class io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing

        fs.listing.filters = []

        ignore.committed.offsets = false

        merge.value.connect.schemas = false

        offset.policy.class = class io.streamthoughts.kafka.connect.filepulse.offset.DefaultSourceOffsetPolicy

        [task.generation.id](http://task.generation.id/) = 0

        task.partitioner.class = class io.streamthoughts.kafka.connect.filepulse.source.DefaultTaskPartitioner

        [tasks.empty.poll.wait.ms](http://tasks.empty.poll.wait.ms/) = 500

        [tasks.file.processing.order.by](http://tasks.file.processing.order.by/) = LAST_MODIFIED

        tasks.file.status.storage.class = class io.streamthoughts.kafka.connect.filepulse.state.KafkaFileObjectStateBackingStore

        tasks.halt.on.error = false

        tasks.reader.class = class io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalBytesArrayInputReader

        topic = harfang-csv2

        value.connect.schema = null

(io.streamthoughts.kafka.connect.filepulse.config.SourceTaskConfig$EnrichedConnectorConfig:354)

[2023-02-06 02:52:23,983] INFO DefaultSourceOffsetPolicyConfig values:

        offset.attributes.string = uri

(io.streamthoughts.kafka.connect.filepulse.offset.DefaultSourceOffsetPolicyConfig:354)

[2023-02-06 02:52:23,984] INFO Retrieving access to shared backing store (io.streamthoughts.kafka.connect.filepulse.state.StateBackingStoreAccess:54)

[2023-02-06 02:52:23,987] INFO CommonFilterConfig values:

        if = null

        ignoreFailure = false

        invert = false

        withOnFailure = null

(io.streamthoughts.kafka.connect.filepulse.config.CommonFilterConfig:354)

[2023-02-06 02:52:23,990] INFO Closing resources FilePulse source task (io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask:337)

[2023-02-06 02:52:23,991] INFO [connect-file-pulse-csv] Releasing access on shared StateBackingStore 'task-thread-connect-file-pulse-csv-0' instance. (io.streamthoughts.kafka.connect.filepulse.state.FileObjectStateBackingStoreManager:93)

[2023-02-06 02:52:23,991] INFO Closed resources FilePulse source task (io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask:359)

[2023-02-06 02:52:23,992] INFO WorkerSourceTask{id=connect-file-pulse-csv-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:488)

[2023-02-06 02:52:23,992] INFO WorkerSourceTask{id=connect-file-pulse-csv-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:505)

[2023-02-06 02:52:23,993] ERROR WorkerSourceTask{id=connect-file-pulse-csv-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:191)

java.lang.NoClassDefFoundError: org/apache/kafka/common/utils/ConfigUtils

        at io.streamthoughts.kafka.connect.filepulse.config.DelimitedRowFilterConfig.<init>(DelimitedRowFilterConfig.java:75)

        at io.streamthoughts.kafka.connect.filepulse.filter.AbstractDelimitedRowFilter.configure(AbstractDelimitedRowFilter.java:66)

        at io.streamthoughts.kafka.connect.filepulse.filter.CSVFilter.configure(CSVFilter.java:63)

        at io.streamthoughts.kafka.connect.filepulse.filter.AbstractRecordFilter.configure(AbstractRecordFilter.java:71)

        at io.streamthoughts.kafka.connect.filepulse.config.SourceTaskConfig.filterByAlias(SourceTaskConfig.java:210)

        at io.streamthoughts.kafka.connect.filepulse.config.SourceTaskConfig.filters(SourceTaskConfig.java:199)

        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.newFileRecordsPollingConsumer(FilePulseSourceTask.java:136)

        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.start(FilePulseSourceTask.java:120)

        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:232)

        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)

        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:239)

        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

        at java.base/java.lang.Thread.run(Thread.java:829)

Caused by: java.lang.ClassNotFoundException: org.apache.kafka.common.utils.ConfigUtils

        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)

        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)

        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)

        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

        ... 16 more

[2023-02-06 02:52:23,996] ERROR WorkerSourceTask{id=connect-file-pulse-csv-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:192)

[2023-02-06 02:52:23,997] INFO Stopping FilePulse source task (io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask:315)

[2023-02-06 02:52:23,997] INFO [Producer clientId=connector-producer-connect-file-pulse-csv-0] Closing the Kafka producer with timeoutMillis = 30000 ms. (org.apache.kafka.clients.producer.KafkaProducer:1189)
```

Is there something wrong in my configuration? It's only when i add the processing filter that the connector does not want to start properly.

Thanks for your help :)

**Comment by fhussonnois** [comment]
Hi @audirline, first thank you very much for your feedback. I'm glad to hear that the connector help you.

Could you tell me what version of FilePulse you are using and what is the version of your Kafka Connect cluster?

Thanks.

**Comment by audirline** [comment]
Hi @fhussonnois ,

No problem keep up the good work ;)

Here is the version i'm using for my testing:

<img width="560" alt="image" src="https://user-images.githubusercontent.com/11729144/217986376-5fa9ee15-afa1-414d-8dac-69fd67e57f7d.png">

I tried with v2.7.0 and also v2.8.0 of the filepulse connector and I had the same error.
