### ISSUE TITLE
Provider "s3" not installed

### ISSUE THREAD

**Issue by srikanthvpai** [streamthoughts/kafka-connect-file-pulse#382]
Hi Team

I am getting this error when I am trying to poll an S3 bucket using this connector.  What additional libraries do I need to add to make this work from S3 bucket ?  Config file attached here.
[filepulseS3.txt](https://github.com/streamthoughts/kafka-connect-file-pulse/files/10712264/filepulseS3.txt)

Where did I go wrong ?

**Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:208)
java.nio.file.FileSystemNotFoundException: Provider "s3" not installed
        at java.base/java.nio.file.Path.of(Path.java:212)
        at java.base/java.nio.file.Paths.get(Paths.java:98)
        at io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalFileStorage.exists(LocalFileStorage.java:62)
        at io.streamthoughts.kafka.connect.filepulse.reader.StorageAwareFileInputReader.canBeRead(StorageAwareFileInputReader.java:41)
        at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.addAll(DefaultFileRecordsPollingConsumer.java:86)
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:162)
        at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.poll(AbstractWorkerSourceTask.java:470)
        at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.execute(AbstractWorkerSourceTask.java:349)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:201)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:256)
        at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.run(AbstractWorkerSourceTask.java:75)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
[2023-02-10 20:11:39,003] INFO [FilePulseConnector_3|task-0] Stopping FilePulse source task (io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask:315)
[2023-02-10 20:11:39,003] INFO [FilePulseConnector_3|task-0] Stopped FilePulse source task. (io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask:326)****

**Comment by OneCricketeer** [comment]
Related #217

**Comment by srikanthvpai** [comment]
@OneCricketeer  Thank you Jordan. The connector started now. Not sure how I missed the documentation. Now it started working. Also do you know what to put in filters.ParseCSVLine.seperator if the line ends simply. Is it \n ?

**Comment by OneCricketeer** [comment]
If there's nothing called artist, then you should remove this from your config

```
"filters.Drop.if": "{{ equals($value.artist, 'U2') }}",
```

**Comment by srikanthvpai** [comment]
> If there's nothing called artist, then you should remove this from your config
> 
> ```
> "filters.Drop.if": "{{ equals($value.artist, 'U2') }}",
> ```

Got it now it started working. Dropped the Drop filter altogether. Thanks for the help @OneCricketeer . Updated in stackoverflow as well.
