### ISSUE TITLE
Record Filtering

### ISSUE THREAD

**Issue by praveent28** [streamthoughts/kafka-connect-file-pulse#39]
{ "CLOG_Objects": { "Record_Id": "74394818", "File": "TypeA", "Record_Data": "" } }
{ "CLOG_Objects": { "Record_Id": "74394818", "File": "TypeB", "Record_Data": "" } }
{ "CLOG_Objects": { "Record_Id": "74394818", "File": "TypeA", "Record_Data": "" } }

We receive the above string data and we want to apply filters on the text ["File":"TypeA"], so the topic would have 2 records and leave out the record which has the text as ["File":"TypeB"].
Would - Drop Filter be a right choice for this and also can regex be used for filtering. How to access the input data in the IF condition to apply the filter. Please help us.

Config file used: 
{"name": "FilePulseConnector","config": {
  "connector.class" : "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
  "key.converter" : "org.apache.kafka.connect.storage.StringConverter",
  "value.converter" : "org.apache.kafka.connect.storage.StringConverter",
  "topic" : "filepulsetopic",
  "internal.kafka.reporter.bootstrap.servers" : "...",
  "fs.scan.directory.path" : "/mnt/KafkaInput",
  "fs.cleanup.policy.class" : "io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy",
  "filters" : "Drop",
  "filters.Drop.type" : "io.streamthoughts.kafka.connect.filepulse.filter.DropFilter",
  "filters.Drop.if" : "{{ contains( {{ CLOG_Objects.File }}, TypeA) }}",
  "filters.Drop.invert" : "true"
}}

Error: 
org.apache.kafka.connect.errors.ConnectException: io.streamthoughts.kafka.connect.filepulse.expression.ExpressionException: Invalid substitution expression : '{{ contains( {{ CLOG_Objects.File }}' (original expression = '{{ contains( {{ CLOG_Objects.File }}, TypeA) }}')
	at io.streamthoughts.kafka.connect.filepulse.config.TaskConfig.filters(TaskConfig.java:155)
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.newFileRecordsPollingConsumer(FilePulseSourceTask.java:89)
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.start(FilePulseSourceTask.java:81)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:213)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.streamthoughts.kafka.connect.filepulse.expression.ExpressionException: Invalid substitution expression : '{{ contains( {{ CLOG_Objects.File }}' (original expression = '{{ contains( {{ CLOG_Objects.File }}, TypeA) }}')
	at io.streamthoughts.kafka.connect.filepulse.expression.parser.regex.RegexExpressionParser.parseExpression(RegexExpressionParser.java:82)
	at io.streamthoughts.kafka.connect.filepulse.expression.parser.regex.RegexExpressionParser.parseExpression(RegexExpressionParser.java:56)
	at io.streamthoughts.kafka.connect.filepulse.filter.condition.ExpressionFilterCondition.<init>(ExpressionFilterCondition.java:46)
	at io.streamthoughts.kafka.connect.filepulse.filter.config.CommonFilterConfig.condition(CommonFilterConfig.java:85)
	at io.streamthoughts.kafka.connect.filepulse.filter.AbstractRecordFilter.configure(AbstractRecordFilter.java:50)
	at io.streamthoughts.kafka.connect.filepulse.config.TaskConfig.filters(TaskConfig.java:152)
	... 10 more

**Comment by fhussonnois** [comment]
Hi @praveent28 , the `DropFilter` is the right choice if your goal is to drop some records based on given `boolean` expression.
The `contains` function should be used to check if an array field's value contains a specific value. So this is not the right function to be used for your context. Instead, you should be able to use one the this following expression : 

* `{{ equals(CLOG_Objects.File, TypeA) }}`
* `{{ matches(CLOG_Objects.File, .*TestA.*) }}`

Note that if your input file contains JSON rows you should the [`JSONFilter`](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters/#jsonfilter) processor to parse the input message.

**Comment by praveent28** [comment]
Hi @fhussonnois,

Thank you for replying, I tried with the below options but it was not successful, need your help: 

1. Used DropFilter but I received error, the config & error are given below:
 Also, I tried with both the options which you suggested and got same errors
Config: 
{"name": "FilePulseConnector","config": {
  "connector.class" : "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
  "key.converter" : "org.apache.kafka.connect.storage.StringConverter",
  "value.converter" : "org.apache.kafka.connect.storage.StringConverter",
  "topic" : "filepulsetopic",
  "internal.kafka.reporter.bootstrap.servers" : "...",
  "fs.scan.directory.path" : "/mnt/KafkaInput",
  "fs.cleanup.policy.class" : "io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy",
  "filters" : "Drop",
  "filters.Drop.if" : "{{ equals(CLOG_Objects.File, TypeA) }}",
  "filters.Drop.type" : "io.streamthoughts.kafka.connect.filepulse.filter.DropFilter",
  "filters.Drop.invert" : "true"
}}
Error:
io.streamthoughts.kafka.connect.filepulse.expression.accessor.AccessException: Cannot access to field 'CLOG_Objects'
	at io.streamthoughts.kafka.connect.filepulse.expression.accessor.TypedStructAccessor.read(TypedStructAccessor.java:72)
	at io.streamthoughts.kafka.connect.filepulse.expression.accessor.TypedStructAccessor.read(TypedStructAccessor.java:66)
	at io.streamthoughts.kafka.connect.filepulse.expression.accessor.TypedStructAccessor.read(TypedStructAccessor.java:27)
	at io.streamthoughts.kafka.connect.filepulse.expression.PropertyExpression.evaluateReaders(PropertyExpression.java:192)
	at io.streamthoughts.kafka.connect.filepulse.expression.PropertyExpression.getValueForProperty(PropertyExpression.java:152)
	at io.streamthoughts.kafka.connect.filepulse.expression.PropertyExpression.readValue(PropertyExpression.java:82)
	at io.streamthoughts.kafka.connect.filepulse.expression.FunctionExpression.readValue(FunctionExpression.java:63)
	at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression$ReplacementExpression.readValue(SubstitutionExpression.java:173)
	at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression.readValue(SubstitutionExpression.java:80)
	at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression.readValue(SubstitutionExpression.java:68)
	at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression.readValue(SubstitutionExpression.java:28)
	at io.streamthoughts.kafka.connect.filepulse.filter.condition.ExpressionFilterCondition.apply(ExpressionFilterCondition.java:65)
	at io.streamthoughts.kafka.connect.filepulse.filter.condition.FilterCondition.lambda$revert$1(FilterCondition.java:45)
	at io.streamthoughts.kafka.connect.filepulse.filter.DropFilter.apply(DropFilter.java:44)
	at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline$FilterNode.apply(DefaultRecordFilterPipeline.java:159)
	at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:131)
	at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:99)
	at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:169)
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:126)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:270)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2. I tried to include both the filters, JSONFilter to parse the input message and DropFilter to filter the records. But the filter does not get applied. Not sure if we can use multiple filters. Please find below the config which I tried and correct me. 
  
Config: 
{"name": "FilePulseConnector","config": {
  "connector.class" : "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
  "key.converter" : "org.apache.kafka.connect.storage.StringConverter",
  "value.converter" : "org.apache.kafka.connect.storage.StringConverter",
  "topic" : "filepulsetopic",
  "internal.kafka.reporter.bootstrap.servers" : "...",
  "fs.scan.directory.path" : "/mnt/KafkaInput",
  "fs.cleanup.policy.class" : "io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy",
  "filters" : "MyJsonFilter",
  "filters.MyJsonFilter.source" : "message",
  "filters.MyJsonFilter.type" : "io.streamthoughts.kafka.connect.filepulse.filter.JSONFilter",
  "filters.Drop.if" : "{{ equals(CLOG_Objects.File, TypeA) }}",
  "filters.Drop.type" : "io.streamthoughts.kafka.connect.filepulse.filter.DropFilter",
  "filters.MyJsonFilter.target" : "payload",
  "filters.Drop.invert" : "true"
}}

- Also I would like to know if the filters can be applied for multiple values, like include rows if values contain TypeA or TypeC.  

Thanks,
Praveen

**Comment by dmarupov** [comment]
> Hi @praveent28 , the `DropFilter` is the right choice if your goal is to drop some records based on given `boolean` expression.
> The `contains` function should be used to check if an array field's value contains a specific value. So this is not the right function to be used for your context. Instead, you should be able to use one the this following expression :
> 
> * `{{ equals(CLOG_Objects.File, TypeA) }}`
> * `{{ matches(CLOG_Objects.File, .*TestA.*) }}`
> 
> Note that if your input file contains JSON rows you should the [`JSONFilter`](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters/#jsonfilter) processor to parse the input message.

Hi @fhussonnois ,

The above mentioned record data: 
{ "CLOG_Objects": { "Record_Id": "74394818", "File": "TypeA", "Record_Data": "" } }
Is in fact a string data. So, in other words even though it is in JSON format it is being passed/processed as a string like so:
"{ "CLOG_Objects": { "Record_Id": "74394818", "File": "TypeA", "Record_Data": "" } }"
Therefore, is there a filter in FilePulse that would filter based on the Regex? 
For example, the data is a plain string, could we say process only those rows of string that contains/includes some {condition}?

Thank you very much!

**Comment by fhussonnois** [comment]
Hi @praveent28 @dmarupov, 

First to apply multiple processing filters you have configure the `filters` with the list of filter aliases. For example : `"filters" : "MyJsonFilter, Drop`. This property also specifies the order in which the filters will be applied.

Below are some relevant links regarding available filters and functions : 
* Available expression function : https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/accessing-data-and-metadata/#builtin-functions
* Available filters : https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters-chain-definition/#available-filters).

There is no dedicated filter to drop records based on a regex, however you should be able to leverage the `DropFilter` and the  the `matches` expression function for that purpose.

If the data is plain string (i.e not parsed with the `JSONFilter`) then the expression should be : `{{ matches(message, .*TestA.*) }}` or more explicitly `{{ matches($value.message, .*TestA.*) }}`

Currenlty, the expression language does not support `or` and `and` operands. But, this can be achieved with the Regex passed to the `matches` expression function.

**Comment by praveent28** [comment]
Thank You! @fhussonnois, the option {{ matches($value.message, .*TestA.*) }} worked for us.
