### ISSUE TITLE
Using MetadataFileInputReader

### ISSUE THREAD

**Issue by iringp** [streamthoughts/kafka-connect-file-pulse#391]
I followed the official Getting Started Guide using a local Confluent Hub with v2.8 of kafka-connect-file-pulse. Everything works. But now I am trying to fetch only metadata of files in a folder, the path+filename, size and timestamp. As no further instruction are provided I tried to use the LocalMetadataFileInputReader. I was hoping that it let me access the mentioned values by default. Silly as I am, I used the "connect-file-pulse-quickstart-raw.json" example and changed the "tasks.reader.class" to "io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalMetadataFileInputReader". With everything running I copied the file "quickstart-musics-dataset.csv" into "/tmp/kafka-connect/examples". This gives me the following output:

`$ kafka-console-consumer --topic quickstart-meta --from-beginning --bootstrap-server localhost:9092
[2023-02-28 15:21:31,595] WARN [Consumer clientId=console-consumer, groupId=console-consumer-19722] Error while fetching metadata with correlation id 2 : {quickstart-meta=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)`

Status topic gives me a failure:
`kafka-console-consumer --topic file-pulse-status-meta --from-beginning --bootstrap-server localhost:9092
{"metadata":{"uri":"file:/tmp/kafka-connect/examples/musics-dataset.csv","name":"musics-dataset.csv","contentLength":6588,"lastModified":1677594128325,"contentDigest":{"digest":"1466679696","algorithm":"CRC32"},"userDefinedMetadata":{"system.inode":1973042,"system.hostname":"LenovoW530"}},"offset":{"position":-1,"rows":0,"timestamp":1677594130119},"status":"SCHEDULED"}
{"metadata":{"uri":"file:/tmp/kafka-connect/examples/musics-dataset.csv","name":"musics-dataset.csv","contentLength":6588,"lastModified":1677594128325,"contentDigest":{"digest":"1466679696","algorithm":"CRC32"},"userDefinedMetadata":{"system.inode":1973042,"system.hostname":"LenovoW530"}},"offset":{"position":-1,"rows":0,"timestamp":1677594130183},"status":"STARTED"}
{"metadata":{"uri":"file:/tmp/kafka-connect/examples/musics-dataset.csv","name":"musics-dataset.csv","contentLength":6588,"lastModified":1677594128325,"contentDigest":{"digest":"1466679696","algorithm":"CRC32"},"userDefinedMetadata":{"system.inode":1973042,"system.hostname":"LenovoW530"}},"offset":{"position":-1,"rows":0,"timestamp":1677594130183},"status":"FAILED"}
{"metadata":{"uri":"file:/tmp/kafka-connect/examples/musics-dataset.csv","name":"musics-dataset.csv","contentLength":6588,"lastModified":1677594128325,"contentDigest":{"digest":"1466679696","algorithm":"CRC32"},"userDefinedMetadata":{"system.inode":1973042,"system.hostname":"LenovoW530"}},"offset":{"position":-1,"rows":0,"timestamp":1677594130183},"status":"CLEANED"}`

What is the right way to use the LocalMetadataFileInputReader? Or is this error kafka related?

**Comment by fhussonnois** [comment]
Hi @iringp, could you please provide the exact connector's configuration you are actually using ?

Also, the status topic indicate a failure. Did you got any ERROR logs ?

**Comment by iringp** [comment]
Thanks for the quick reply. This is the config:
`{
  "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
  "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.fs.clean.DeleteCleanupPolicy",
  "fs.listing.class": "io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing",
  "fs.listing.directory.path":"/tmp/kafka-connect/examples/",
  "fs.listing.filters":"io.streamthoughts.kafka.connect.filepulse.fs.filter.RegexFileListFilter",
  "fs.listing.interval.ms": "10000",
  "file.filter.regex.pattern":".*\\.csv$",
  "skip.headers": "1",
  "topic": "quickstart-meta",
  "tasks.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalMetadataFileInputReader",
  "tasks.file.status.storage.class": "io.streamthoughts.kafka.connect.filepulse.state.KafkaFileObjectStateBackingStore",
  "tasks.file.status.storage.bootstrap.servers": "localhost:9092",
  "tasks.file.status.storage.topic": "file-pulse-status-meta",
  "tasks.file.status.storage.topic.partitions": 1,
  "tasks.file.status.storage.topic.replication.factor": 1,
  "tasks.max": 1
}`

I noticed some errors in connect. But the log is very big. So I copied a few interesting lines, but I am not sure where the problem starts:
`[2023-03-01 14:01:58,580] INFO [quickstart-meta|task-0] Opening new iterator for: file:/tmp/kafka-connect/examples/musics-dataset.csv (io.streamthoughts.kafka.connect.filepulse.source.DelegateFileInputIterator:84)
[2023-03-01 14:01:58,631] INFO [quickstart-meta|task-0] Closed iterator for: [uri=file:/tmp/kafka-connect/examples/musics-dataset.csv, name='musics-dataset.csv', contentLength=6588, lastModified=1677675709422, contentDigest=[digest=1466679696, algorithm='CRC32'], userDefinedMetadata={system.inode=2402570, system.hostname=LenovoW530}]  (io.streamthoughts.kafka.connect.filepulse.source.DelegateFileInputIterator:156)
[2023-03-01 14:01:58,632] ERROR [quickstart-meta|task-0] Error while processing object-file: '[uri=file:/tmp/kafka-connect/examples/musics-dataset.csv, name='musics-dataset.csv', contentLength=6588, lastModified=1677675709422, contentDigest=[digest=1466679696, algorithm='CRC32'], userDefinedMetadata={system.inode=2402570, system.hostname=LenovoW530}]' (io.streamthoughts.kafka.connect.filepulse.source.FileObjectStateReporter:122)
io.streamthoughts.kafka.connect.filepulse.errors.ConnectFilePulseException: Failed to convert data into Kafka Connect record at offset [position=-1, rows=-1, timestamp=1677675718591] from object-file: [uri=file:/tmp/kafka-connect/examples/musics-dataset.csv, name='musics-dataset.csv', contentLength=6588, lastModified=1677675709422, contentDigest=[digest=1466679696, algorithm='CRC32'], userDefinedMetadata={system.inode=2402570, system.hostname=LenovoW530}]'
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.buildSourceRecord(FilePulseSourceTask.java:336)
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.lambda$poll$0(FilePulseSourceTask.java:222)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1033)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:223)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.poll(AbstractWorkerSourceTask.java:470)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.execute(AbstractWorkerSourceTask.java:349)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:201)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:256)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.run(AbstractWorkerSourceTask.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.DataException: Invalid Java object for schema with type STRING: class java.lang.Long
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:242)
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:213)
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:261)
	at org.apache.kafka.connect.data.Struct.put(Struct.java:216)
	at io.streamthoughts.kafka.connect.filepulse.source.internal.ConnectSchemaMapper.toConnectStruct(ConnectSchemaMapper.java:274)
	at io.streamthoughts.kafka.connect.filepulse.source.internal.ConnectSchemaMapper.map(ConnectSchemaMapper.java:215)
	at io.streamthoughts.kafka.connect.filepulse.source.internal.ConnectSchemaMapper.map(ConnectSchemaMapper.java:199)
	at io.streamthoughts.kafka.connect.filepulse.source.TypedFileRecord.lambda$toSourceRecord$1(TypedFileRecord.java:99)
	at io.streamthoughts.kafka.connect.filepulse.source.internal.InternalSourceRecordBuilder.build(InternalSourceRecordBuilder.java:55)
	at io.streamthoughts.kafka.connect.filepulse.source.TypedFileRecord.toSourceRecord(TypedFileRecord.java:103)
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.buildSourceRecord(FilePulseSourceTask.java:316)
	... 20 more
[2023-03-01 14:01:58,633] ERROR [quickstart-meta|task-0] Caught unexpected error while processing file. Ignore and continue (io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask:237)
io.streamthoughts.kafka.connect.filepulse.errors.ConnectFilePulseException: Failed to convert data into Kafka Connect record at offset [position=-1, rows=-1, timestamp=1677675718591] from object-file: [uri=file:/tmp/kafka-connect/examples/musics-dataset.csv, name='musics-dataset.csv', contentLength=6588, lastModified=1677675709422, contentDigest=[digest=1466679696, algorithm='CRC32'], userDefinedMetadata={system.inode=2402570, system.hostname=LenovoW530}]'
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.buildSourceRecord(FilePulseSourceTask.java:336)
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.lambda$poll$0(FilePulseSourceTask.java:222)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1033)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:223)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.poll(AbstractWorkerSourceTask.java:470)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.execute(AbstractWorkerSourceTask.java:349)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:201)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:256)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.run(AbstractWorkerSourceTask.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.DataException: Invalid Java object for schema with type STRING: class java.lang.Long
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:242)
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:213)
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:261)
	at org.apache.kafka.connect.data.Struct.put(Struct.java:216)
	at io.streamthoughts.kafka.connect.filepulse.source.internal.ConnectSchemaMapper.toConnectStruct(ConnectSchemaMapper.java:274)
	at io.streamthoughts.kafka.connect.filepulse.source.internal.ConnectSchemaMapper.map(ConnectSchemaMapper.java:215)
	at io.streamthoughts.kafka.connect.filepulse.source.internal.ConnectSchemaMapper.map(ConnectSchemaMapper.java:199)
	at io.streamthoughts.kafka.connect.filepulse.source.TypedFileRecord.lambda$toSourceRecord$1(TypedFileRecord.java:99)
	at io.streamthoughts.kafka.connect.filepulse.source.internal.InternalSourceRecordBuilder.build(InternalSourceRecordBuilder.java:55)
	at io.streamthoughts.kafka.connect.filepulse.source.TypedFileRecord.toSourceRecord(TypedFileRecord.java:103)
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.buildSourceRecord(FilePulseSourceTask.java:316)
	... 20 more`
