### ISSUE TITLE
Unable to read 5 GB zip file from S3 bucket

### ISSUE THREAD

**Issue by shubham-cldcvr** [streamthoughts/kafka-connect-file-pulse#413]
**Describe the bug**
I have 5 GB of zip files in s3 bucket that contains images and I am using s3 source connector. But getting an below error.

[2023-03-14 16:29:15,866] WARN [s3-src|task-0] Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use. (com.amazonaws.services.s3.internal.S3AbortableInputStream:178)
[2023-03-14 16:29:15,869] ERROR [s3-src|task-0] WorkerSourceTask{id=s3-src-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:210)
**java.lang.OutOfMemoryError: Required array size too large**
        at java.base/java.io.InputStream.readNBytes(InputStream.java:404)
        at java.base/java.io.InputStream.readAllBytes(InputStream.java:333)
        at io.streamthoughts.kafka.connect.filepulse.fs.reader.text.BytesArrayInputIterator.next(BytesArrayInputIterator.java:85)
        at io.streamthoughts.kafka.connect.filepulse.source.DelegateFileInputIterator.next(DelegateFileInputIterator.java:137)
        at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:173)
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:219)
        at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.poll(AbstractWorkerSourceTask.java:457)
        at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.execute(AbstractWorkerSourceTask.java:351)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
        at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.run(AbstractWorkerSourceTask.java:75)
        at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
[2023-03-14 16:29:15,870] INFO [s3-src|task-0] Stopping FilePulse source task (io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask:368)
[2023-03-14 16:29:15,870] INFO [s3-src|task-0] Closing resources FilePulse source task (io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask:393)

**To Reproduce**
I am using below configuration:
`{
  "name": "s3-src",
  "config": {
    "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
    "fs.listing.class": "io.streamthoughts.kafka.connect.filepulse.fs.AmazonS3FileSystemListing",
    "tasks.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.reader.AmazonS3BytesArrayInputReader",
    "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.fs.clean.LogCleanupPolicy",
    "taws.access.key.id": "<ACCESS_KEY>",
    "aws.secret.access.key": "<SECRET_KEY>",
    "aws.secret.session.token": "<SESSION_TOKEN>",
    "topic": "<TOPIC>",
    "aws.s3.region": "<REGION>",
    "aws.s3.bucket.name": "<BUCKET>",
    "tasks.file.status.storage.bootstrap.servers": "<BOOTSTRAP_SERVER:PORT>",
    "tasks.file.status.storage.security.protocol": "SASL_SSL",
    "tasks.file.status.storage.sasl.mechanism": "SCRAM-SHA-256",
    "tasks.file.status.storage.ssl.protocol": "TLS",
    "tasks.file.status.storage.ssl.keystore.type": "PKCS12",
    "tasks.file.status.storage.ssl.keystore.location": "/root/kafka_2.13-3.4.0/certsfolder/client.keystore.p12",
    "tasks.file.status.storage.ssl.keystore.password": "password",
    "tasks.file.status.storage.ssl.key.password": "password",
    "tasks.file.status.storage.ssl.truststore.location": "/root/kafka_2.13-3.4.0/certsfolder/client.truststore.jks",
    "tasks.file.status.storage.ssl.truststore.password": "password",
    "tasks.file.status.storage.ssl.truststore.type": "JKS",
    "tasks.file.status.storage.consumer.security.protocol": "SASL_SSL",
    "tasks.file.status.storage.consumer.sasl.mechanism": "SCRAM-SHA-256",
    "tasks.file.status.storage.producer.security.protocol": "SASL_SSL",
    "tasks.file.status.storage.producer.sasl.mechanism": "SCRAM-SHA-256",
    "tasks.file.status.storage.consumer.ssl.keystore.type": "PKCS12",
    "tasks.file.status.storage.consumer.ssl.keystore.location": "/root/kafka_2.13-3.4.0/certsfolder/client.keystore.p12",
    "tasks.file.status.storage.consumer.ssl.keystore.password": "password",
    "tasks.file.status.storage.consumer.ssl.key.password": "password",
    "tasks.file.status.storage.consumer.ssl.truststore.location": "/root/kafka_2.13-3.4.0/certsfolder/client.truststore.jks",
    "tasks.file.status.storage.consumer.ssl.truststore.password": "password",
    "tasks.file.status.storage.consumer.ssl.truststore.type": "JKS",
    "tasks.file.status.storage.producer.ssl.keystore.type": "PKCS12",
    "tasks.file.status.storage.producer.ssl.keystore.location": "/root/kafka_2.13-3.4.0/certsfolder/client.keystore.p12",
    "tasks.file.status.storage.producer.ssl.keystore.password": "password",
    "tasks.file.status.storage.producer.ssl.key.password": "password",
    "tasks.file.status.storage.producer.ssl.truststore.location": "/root/kafka_2.13-3.4.0/certsfolder/client.truststore.jks",
    "tasks.file.status.storage.producer.ssl.truststore.password": "password",
    "tasks.file.status.storage.producer.ssl.truststore.type": "JKS"

  }
}`

**Expected behavior**
Connector should read the zip file and ingest it into the kafka topic.
**(NOTE: When I uploaded the small zip file with images then it worked.)**

**Comment by loquisgon** [comment]
It looks like your connector is running out of memory, can you try adding more memory?
`java.lang.OutOfMemoryError: Required array size too large`

**Comment by shubham-cldcvr** [comment]
@loquisgon 
Could You please describe where and how I can do it?

**Comment by fhussonnois** [comment]
Hi @shubham-cldcvr, you have configured the connector to use : 

`"tasks.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.reader.AmazonS3BytesArrayInputReader"` 

Thus, the `AmazonS3BytesArrayInputReader` will load the entire file into memory (i.e., `InputStream#readAllBytes()`).
