### ISSUE TITLE
Multiple JSON file as input

### ISSUE THREAD

**Issue by mohai-kafka** [streamthoughts/kafka-connect-file-pulse#47]
I need to read json file and send it to Kafka topic based on file pattern. like

If json file name contain a_ (a_sample.json) then this needs to goto x topic
If json file name contain b_ (b_sample.json) then this needs to goto y topic

Is file pulse connect support this? If yes,could you please guide me. Thanks.

Mohaideen S.

**Comment by fhussonnois** [comment]
Hi @mohai-kafka, yes this should be possible using the file-pulse [`AppendFilter`](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters/#appendfilter) and [Simple Connect Expression](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/accessing-data-and-metadata/).

Here is an example that shows how to achieve what you are asking : 

```
# defines the filter chain to execute on each record (i.e the filter aliases)
filters=SetTopicX

# set the filter type for the alias `SetTopX`
filters.SetTopicX.type=io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter

# set the filter to be apply only on record from a file name starting with a_
filters.SetTopicX.if={{ matches( $metadata.name,  ^a_.*) }}

# select the output as the topic
filters.SetTopicX.field={{ $topic }}

# set the name of the output topic
filters.SetTopicX.value=x
```

**Comment by mohai-kafka** [comment]
Thanks for your information. My first question is File Pulse support .json file extension as input?

**Comment by fhussonnois** [comment]
Yes, for reading JSON input files you should have to use the either the [RowFileInputReader](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/file-readers/#rowfileinputreader-default) or [BytesArrayInputReader](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/file-readers/#bytesarrayinputreader) with the [JSONFilter](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters/#jsonfilter)

**Comment by mohai-kafka** [comment]
I tried based on your recommendation but getting below error message.

[2020-08-03 18:11:03,375] ERROR [coverage-etl-filepulse-source-connect-deva|task-0] Error occurred while executing filter 'JSONFilter' on record='[message=[value=[B@3d00258, schema =[type=BYTES]]]' (io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline:180)
[2020-08-03 18:11:03,375] ERROR [coverage-etl-filepulse-source-connect-deva|task-0] Error while processing source file '[name='NEXUSCOVBATCH_EMPR_SUB_GRP_20200727_2.json', path='/opt/kafka/confluent/coveragetmp', size=21351, lastModified=1596127207000, inode=6150198, hash=4246012737]' (io.streamthoughts.kafka.connect.filepulse.source.KafkaFileStateReporter:119)
io.streamthoughts.kafka.connect.filepulse.data.DataException: subgroupDetails is not a valid field name
        at io.streamthoughts.kafka.connect.filepulse.data.TypedStruct.lookupField(TypedStruct.java:347)
        at io.streamthoughts.kafka.connect.filepulse.data.TypedStruct.get(TypedStruct.java:237)
        at io.streamthoughts.kafka.connect.filepulse.filter.JSONFilter.apply(JSONFilter.java:66)
        at io.streamthoughts.kafka.connect.filepulse.filter.AbstractMergeRecordFilter.apply(AbstractMergeRecordFilter.java:51)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline$FilterNode.apply(DefaultRecordFilterPipeline.java:159)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:131)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:99)
        at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:169)
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:126)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:270)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:237)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

My Connector config and data file attached for your reference.
[ConnectConfig.json.txt](https://github.com/streamthoughts/kafka-connect-file-pulse/files/5019076/ConnectConfig.json.txt)
[ConnectConfig.json.txt](https://github.com/streamthoughts/kafka-connect-file-pulse/files/5019085/ConnectConfig.json.txt)
[source.txt](https://github.com/streamthoughts/kafka-connect-file-pulse/files/5019086/source.txt)


is below

**Comment by mohai-kafka** [comment]
Can i get you guys thought on this issue?

**Comment by fhussonnois** [comment]
Hi @mohai-kafka, after looking to the code of the `JSONFilter` it seems it cannot read a value of type BYTES. So, I will push a fix for that. But, your configuration is not correct. 

```json
"filters":"MyJsonFilter",
"filters.MyJsonFilter.type":"io.streamthoughts.kafka.connect.filepulse.filter.JSONFilter",
"filters.MyJsonFilter.source":"message",
"filters.MyJsonFilter.target":"payload"
```

In addition, I've seen your file contains an JSON Array, do you need to get one record per element ? Because, there is no filter for exploding an array to multiple records

**Comment by mohai-kafka** [comment]
Thanks for your reply. I tried with "filters.MyJsonFilter.source":"message" and got same issue.  Yes I need one record per element.

**Comment by fhussonnois** [comment]
Could you give me the exception your got with `filters.MyJsonFilter.source":"message" ` ?

**Comment by mohai-kafka** [comment]
[2020-08-06 10:52:58,511] ERROR [coverage-etl-filepulse-source-connect-deva|task-0] Error while processing source file '[name='NEXUSCOVBATCH_EMPR_SUB_GRP_20200727_3.json', path='/opt/kafka/confluent/coveragetmp', size=21351, lastModified=1596127207000, inode=6150198, hash=4246012737]' (io.streamthoughts.kafka.connect.filepulse.source.KafkaFileStateReporter:119)
io.streamthoughts.kafka.connect.filepulse.filter.FilterException: Invalid field 'message', cannot convert field of type 'BYTES'
        at io.streamthoughts.kafka.connect.filepulse.filter.JSONFilter.checkType(JSONFilter.java:87)
        at io.streamthoughts.kafka.connect.filepulse.filter.JSONFilter.apply(JSONFilter.java:69)
        at io.streamthoughts.kafka.connect.filepulse.filter.AbstractMergeRecordFilter.apply(AbstractMergeRecordFilter.java:51)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline$FilterNode.apply(DefaultRecordFilterPipeline.java:159)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:131)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:99)
        at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:169)
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:126)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:270)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:237)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by fhussonnois** [comment]
Thanks @mohai-kafka. I pushed two commits to solve your problem #51 and #52 that will be available in the next version. File Pulse `v1.4.0` shoud be released soon.

**Comment by mohai-kafka** [comment]
Thanks @fhussonnois . for time being i am using RowFileInputReader. I am seeing some weird behavior. 

When  i use RowFileInputReader I am seeing different issues. Attached in the file.
[Information.txt](https://github.com/streamthoughts/kafka-connect-file-pulse/files/5035854/Information.txt)

**Comment by fhussonnois** [comment]
Ok this is a bug due to the JSONFilter that do not infer the schema for array of complex type. I will provide a fix for that.

**Comment by mohai-kafka** [comment]
THanks a lot for your help. May i know when 1.4.0 going to release with these fixes and enhancements?

**Comment by fhussonnois** [comment]
@mohai-kafka, v1.4.0 is available : https://github.com/streamthoughts/kafka-connect-file-pulse/releases/tag/v1.4.0
However, this new release is currently not available on confluent-hub

**Comment by mohai-kafka** [comment]
Thanks for your quick response. After i took new version. I am getting following error. Error contains my json message also.

[2020-08-06 18:21:26,190] ERROR [coverage-etl-filepulse-source-connect-deva|task-0] Error occurred while executing filter 'JSONFilter' on record='[message=[value=[B@39734f6, schema =[type=BYTES]]]' (io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline:180)
[2020-08-06 18:21:26,190] ERROR [coverage-etl-filepulse-source-connect-deva|task-0] Error while processing source file '[name='sampleetl_8.json', path='/opt/kafka/confluent/coveragetmp', size=2109, lastModified=1596752452000, inode=6150846, hash=218583862]' (io.streamthoughts.kafka.connect.filepulse.source.KafkaFileStateReporter:119)
io.streamthoughts.kafka.connect.filepulse.filter.FilterException: Error while reading json value, invalid JSON message.
        at io.streamthoughts.kafka.connect.filepulse.filter.JSONFilter.apply(JSONFilter.java:78)
        at io.streamthoughts.kafka.connect.filepulse.filter.AbstractMergeRecordFilter.apply(AbstractMergeRecordFilter.java:51)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline$FilterNode.apply(DefaultRecordFilterPipeline.java:159)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:131)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:99)
        at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:169)
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:126)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:270)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:237)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.jsoniter.spi.JsonException: readObject: expect { or , or } or n, but found: [, head: 1, peek: [, buf: [{
    "sourceSystemMemberId":"211365001",
    "sourceSystemCode":"171",
    "addressTypeCode":"05",
    "addressDetails":[{
        "addressTypeCode": "05",
        "addresstypeDescription": "HOME",
        "address":{
            "line1": "1180 Martins Avenue",
            "line2": "",
            "line3": "",
            "city": "Washington",
            "county": "Dis",
            "state": "DC",
            "country": "US",
            "zipCode": "20001"

            },
        "uspsAddress":{
            "uspsLine1": "1180 Martins Avenue",
            "uspsLine2": "",
            "uspsLine3": "",
            "uspsCity": "Washington",
            "uspsCounty": "Distr",
            "uspsCountyName": "District Of Columbia",
            "uspsState": "DC",
            "uspsCountry": "US",
            "uspsZipCode": "20001",
            "uspsZipFourCode": "",
            "uspsAddrValidatnCompltdInd": "N"
            },
        "srcLvlCode": "H",
        "membConfidentialityInd": "N"
    }]
},
{
    "sourceSystemMemberId":"211365002",
    "sourceSystemCode":"171",
    "addressTypeCode":"05",
    "addressDetails":[{
        "addressTypeCode": "05",
        "addresstypeDescription": "HOME",
        "address":{
            "line1": "1180 Martins Avenue",
            "line2": "",
            "line3": "",
            "city": "Washington",
            "county": "Dis",
            "state": "DC",
            "country": "US",
            "zipCode": "20001"

            },
        "uspsAddress":{
            "uspsLine1": "1180 Martins Avenue",
            "uspsLine2": "",
            "uspsLine3": "",
            "uspsCity": "Washington",
            "uspsCounty": "Distr",
            "uspsCountyName": "District Of Columbia",
            "uspsState": "DC",
            "uspsCountry": "US",
            "uspsZipCode": "20001",
            "uspsZipFourCode": "",
            "uspsAddrValidatnCompltdInd": "N"
            },
        "srcLvlCode": "H",
        "membConfidentialityInd": "N"
    }]
}
]
        at com.jsoniter.JsonIterator.reportError(JsonIterator.java:136)
        at com.jsoniter.IterImplObject.readObject(IterImplObject.java:36)
        at com.jsoniter.JsonIterator.readObject(JsonIterator.java:214)
        at io.streamthoughts.kafka.connect.filepulse.json.DefaultJSONStructConverter$ObjectJsonFieldAccessor.read(DefaultJSONStructConverter.java:152)
        at io.streamthoughts.kafka.connect.filepulse.json.DefaultJSONStructConverter.readJson(DefaultJSONStructConverter.java:76)
        at io.streamthoughts.kafka.connect.filepulse.filter.JSONFilter.apply(JSONFilter.java:71)
        ... 15 more
[2020-08-06 18:21:26,191] INFO [coverage-etl-filepulse-source-connect-deva|task-0] Orphan task detected - all scheduled files are now completed - waiting for new reconfiguration. (io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask:119)
[2020-08-06 18:21:30,043] INFO [coverage-etl-filepulse-source-connect-deva|worker] Cleaning up completed files '1' (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner:201)
[2020-08-06 18:21:30,044] INFO [coverage-etl-filepulse-source-connect-deva|worker] Failure : [metadata=[name='sampleetl_8.json', path='/opt/kafka/confluent/coveragetmp', size=2109, lastModified=1596752452000, inode=6150846, hash=218583862], offset=[position=-1, rows=0, timestamp=1596752486189], status=FAILED, props={hostname=ip-10-136-132-222}] (io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy:54)

**Comment by fhussonnois** [comment]
The error is due to invalid JSON which reader are you using `RowFileInputReader` or `BytesArrayInputReader` ? The JSON input seems to be formatted so you should use the ` BytesArrayInputReader`

**Comment by mohai-kafka** [comment]
I am using BytesArrayInputReader

**Comment by fhussonnois** [comment]
Hi @mohai-kafka, I've found the problem. Currenlty the JSONFilter doesn't support Array JSON only record. I will provide a fix for that.

**Comment by mohai-kafka** [comment]
Thanks. I hope it split in array element in to one message. In my example I
get 2 message in topic?. When I receive I need only payload.

**Comment by mohai-kafka** [comment]
> {{ matches( $metadata.name,  ^a_.*) }}

When i use Appendfilter i am getting following error.

[2020-08-09 21:22:04,642] INFO [coverage.basecoverage-file-source-deva|task-0] Opening new iterator for source : [name='NEXUSCOVBATCH_MEMB_PLAN_COV_4.json', path='/mnt/nexus-kafka-connect/member-coverage/MEMBPLANCOV/deva', size=43516, lastModified=1597022524000, inode=25, hash=880644864] (io.streamthoughts.kafka.connect.filepulse.source.FileInputIterable:65)
[2020-08-09 21:22:04,668] ERROR [coverage.basecoverage-file-source-deva|task-0] Error occurred while executing filter 'AppendFilter' on record='[message=[value=[B@f9f9858, schema =[type=BYTES]]]' (io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline:180)
[2020-08-09 21:22:04,668] ERROR [coverage.basecoverage-file-source-deva|task-0] Error while processing source file '[name='NEXUSCOVBATCH_MEMB_PLAN_COV_4.json', path='/mnt/nexus-kafka-connect/member-coverage/MEMBPLANCOV/deva', size=43516, lastModified=1597022524000, inode=25, hash=880644864]' (io.streamthoughts.kafka.connect.filepulse.source.KafkaFileStateReporter:119)
java.lang.NullPointerException
[2020-08-09 21:22:04,669] INFO [coverage.basecoverage-file-source-deva|task-0] WorkerSourceTask{id=coverage.basecoverage-file-source-deva-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:424)
[2020-08-09 21:22:04,669] INFO [coverage.basecoverage-file-source-deva|task-0] WorkerSourceTask{id=coverage.basecoverage-file-source-deva-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:441)
[2020-08-09 21:22:04,669] ERROR [coverage.basecoverage-file-source-deva|task-0] WorkerSourceTask{id=coverage.basecoverage-file-source-deva-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:186)
io.streamthoughts.kafka.connect.filepulse.errors.ConnectFilePulseException: java.lang.NullPointerException
        at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:188)
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:126)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:270)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:237)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
[2020-08-09 21:22:04,669] ERROR [coverage.basecoverage-file-source-deva|task-0] WorkerSourceTask{id=coverage.basecoverage-file-source-deva-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:187)

My configuration is  below. 

    "task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.BytesArrayInputReader",
    "filters":"SetSUBGRPTopic",
    "filters.SetSUBGRPTopic.type":"io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter",
    "filters.SetSUBGRPTopic.if":"{{ matches($metadata.name,^NEXUSCOVBATCH_MEMB_PLAN_COV_.*) }}",
    "filters.SetSUBGRPTopic.field":"{{ $topic }}",
    "filters.SetSUBGRPTopic.value":"member.coverage.domain.deva.basecoverage"

**Comment by mohai-kafka** [comment]
THanks @fhussonnois . May i know when can you are going to release these issue fixes for use?

**Comment by fhussonnois** [comment]
Hi @mohai-kafka, File Pulse v1.4.1 is released. Just note this version comes with somes changes on the expression language. Do not hesite to open a separate issue if you have trouble with it.
