### ISSUE TITLE
Error XML File Ingestion: org.apache.avro.SchemaParseException: Illegal initial character: #text

### ISSUE THREAD

**Issue by hirsche** [streamthoughts/kafka-connect-file-pulse#50]
Hi,

I am ingesting XML Files with the following structure

```xml
<root>
  <document>
    <paragraph id="1">
      <sentence id="1">
        <content>Perfectly equipped.</content>
        <topic_gold>24</topic_gold>
      </sentence>
      <sentence id="2">
        <content>[...TEXT TO SELECT...]</content>
        <topic_gold>24</topic_gold>
        <subTopic_gold>24</subTopic_gold>
        <sentiment_gold>-1</sentiment_gold>
      </sentence>
      
      [sentence*]

    </paragraph>
    
     [paragraph*]
</root>
```

querying with the following xpath

```xpath
//root/document/paragraph/sentence/topic_gold[text()=24]/parent::node()/content/text()
```

for the text in the content element where <topic_gold> has the text value 24. This query gives me the following error:

```
connect            | org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
connect            |    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
connect            |    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
connect            |    at org.apache.kafka.connect.runtime.WorkerSourceTask.convertTransformedRecord(WorkerSourceTask.java:270)
connect            |    at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:294)
connect            |    at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:229)
connect            |    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
connect            |    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
connect            |    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
connect            |    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
connect            |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
connect            |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
connect            |    at java.lang.Thread.run(Thread.java:748)
connect            | Caused by: org.apache.avro.SchemaParseException: Illegal initial character: #text
connect            |    at org.apache.avro.Schema.validateName(Schema.java:1147)
connect            |    at org.apache.avro.Schema.access$200(Schema.java:81)
connect            |    at org.apache.avro.Schema$Name.<init>(Schema.java:489)
connect            |    at org.apache.avro.Schema.createRecord(Schema.java:161)
connect            |    at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:893)
connect            |    at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:732)
connect            |    at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:726)
connect            |    at io.confluent.connect.avro.AvroData.fromConnectData(AvroData.java:365)
connect            |    at io.confluent.connect.avro.AvroConverter.fromConnectData(AvroConverter.java:77)
connect            |    at org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$2(WorkerSourceTask.java:270)
connect            |    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
connect            |    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
connect            |    ... 11 more
```

When removing `\text()` at the end, querying just for the element the request works fine and the file gets processed. The problem then is that the text written to the topic has strange characters in it, which seem to be character conversion/encoding problems of characters like "</>".

Could you kindly assist why the original xpath query is not working? The XML File syntactically correct which I've checked multiple times already. Is this a bug or am I doing something wrong here?

Thanks
Eduard

**Comment by hirsche** [comment]
Ok, I think I understand that this is caused by the xpath query which only returns text and has no "structure". But would it be possible to write those test result in a plain-text based topic?

**Comment by fhussonnois** [comment]
Hi @hirsche, the `XMLFileInputReader` expects the configured xpath to return a NodeSet. Then each element is processed as a single record. So using your example, if you used the following xpath `//root/document/paragraph/sentence/topic_gold[text()=24]/parent::node()/content` this will produce two records

`{"content":"Perfectly equipped."}`
`{"content":"[...TEXT TO SELECT...]"}`

If would like to send plain-text into Kafka you can use Connect Single Message Transformer (SMT) such as :  [ExtractField](https://docs.confluent.io/current/connect/transforms/extractfield.html#extractfield)

**Comment by hirsche** [comment]
Ok I think I've missed that part in the documentation. 
Thx
