### ISSUE TITLE
MalformedJsonException while Creating new Google Cloud Storage service using the the credentials JSON 

### ISSUE THREAD

**Issue by utkarshnehete** [streamthoughts/kafka-connect-file-pulse#582]
Getting below exception while creating Connector for reading files from Google Storage. 

[2023-12-15 11:18:48,135] INFO [connect-file-pulse-quickstart-csv|worker] Creating new Google Cloud Storage service using the the credentials JSON that was passed through the connector's configuration (io.streamthoughts.kafka.connect.filepulse.fs.GcsClientUtils:69)
[2023-12-15 11:18:48,145] ERROR [connect-file-pulse-quickstart-csv|worker] Failed to read credentials from JSON string (io.streamthoughts.kafka.connect.filepulse.fs.GcsClientUtils:106)
com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1465)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:602)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433)
	at com.google.api.client.json.gson.GsonParser.nextToken(GsonParser.java:149)
	at com.google.api.client.json.JsonParser.startParsing(JsonParser.java:213)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:358)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:335)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:79)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:73)
	at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:166)
	at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:143)
	at io.streamthoughts.kafka.connect.filepulse.fs.GcsClientUtils.getCredentialsFromJson(GcsClientUtils.java:104)
	at io.streamthoughts.kafka.connect.filepulse.fs.GcsClientUtils.createStorageService(GcsClientUtils.java:73)
	at io.streamthoughts.kafka.connect.filepulse.fs.GcsFileSystemListing.configure(GcsFileSystemListing.java:46)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:401)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:433)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:418)
	at io.streamthoughts.kafka.connect.filepulse.config.CommonSourceConfig.getFileSystemListing(CommonSourceConfig.java:277)
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector.createFileSystemMonitor(FilePulseSourceConnector.java:128)
	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector.start(FilePulseSourceConnector.java:111)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:192)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:217)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:376)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:357)
	at org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:144)
	at org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:122)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

Below is the connector configuration

name=connect-file-pulse-quickstart-csv
connector.class=io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector
topic=connect-file-pulse-quickstart-csv
tasks.max=2

filters=ParseDelimitedRow

tasks.reader.class=io.streamthoughts.kafka.connect.filepulse.fs.reader.GcsRowFileInputReader

filters.ParseDelimitedRow.trim.column=true
filters.ParseDelimitedRow.type=io.streamthoughts.kafka.connect.filepulse.filter.CSVFilter
filters.ParseDelimitedRow.skip.headers=0
filters.ParseDelimitedRow.auto.generate.column.names=true
filters.ParseDelimitedRow.separator=~

fs.listing.class=io.streamthoughts.kafka.connect.filepulse.fs.GcsFileSystemListing
gcs.credentials.json=.config/gcloud
gcs.bucket.name=epricing-376304
fs.listing.interval.ms=10000
fs.listing.directory.path=tmp/samplefiles/
fs.listing.recursive.enabled=true
fs.listing.filters=io.streamthoughts.kafka.connect.filepulse.fs.filter.RegexFileListFilter
file.filter.regex.pattern=.*\\.dat$

fs.cleanup.policy.class=io.streamthoughts.kafka.connect.filepulse.fs.clean.LogCleanupPolicy

tasks.file.status.storage.bootstrap.servers=localhost:9092
tasks.file.status.storage.topic=connect-file-pulse-status

offset.attributes.string=name+hash

**Comment by utkarshnehete** [comment]
My bad.. Issue was because of incorrect config... was incorrectly using gcs.credentials.json=.config/gcloud instead of gcs.credentials.path=.config/gcloud
