### ISSUE TITLE
XMLFileInputReader: Unsupported node type '4'

### ISSUE THREAD

**Issue by ccamba** [streamthoughts/kafka-connect-file-pulse#64]
Hi, I have a xml file with this structure:

```
<?xml version="1.0" encoding="iso-8859-1"?>
<ROWSET>
 <ROW>
 <EP_EXPEDIENTE>FOO</EP_EXPEDIENTE>
 <EP_EMAIL><![CDATA[foo@foo.com]]></EP_EMAIL>
 </ROW>
</ROWSET>
```

But the reader gives an error when it wants to parse CDATA

Stack:
`
[2020-08-13 17:41:39,808] ERROR WorkerSourceTask{id=connect-file-pulse-xml-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
io.streamthoughts.kafka.connect.filepulse.reader.ReaderException: Unsupported node type '4'
        at io.streamthoughts.kafka.connect.filepulse.reader.XMLFileInputReader$Node2StructConverter.readNodeObject(XMLFileInputReader.java:210)
        at io.streamthoughts.kafka.connect.filepulse.reader.XMLFileInputReader$Node2StructConverter.convertNodeObjectTree(XMLFileInputReader.java:160)
        at io.streamthoughts.kafka.connect.filepulse.reader.XMLFileInputReader$Node2StructConverter.readNodeObject(XMLFileInputReader.java:207)
        at io.streamthoughts.kafka.connect.filepulse.reader.XMLFileInputReader$Node2StructConverter.convertNodeObjectTree(XMLFileInputReader.java:160)
        at io.streamthoughts.kafka.connect.filepulse.reader.XMLFileInputReader$Node2StructConverter.access$000(XMLFileInputReader.java:152)
        at io.streamthoughts.kafka.connect.filepulse.reader.XMLFileInputReader$XMLFileInputIterator.next(XMLFileInputReader.java:139)
        at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:165)
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:126)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:245)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:221)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

You must add in line 95 of https://github.com/streamthoughts/kafka-connect-file-pulse/blob/d0c7a9d9cc6814a38a95c62a3972590d9ae17b14/connect-file-pulse-plugin/src/main/java/io/streamthoughts/kafka/connect/filepulse/reader/XMLFileInputReader.java#L94
**builderFactory.setCoalescing(true);**

And it will works fine or if I can configure it in an external configuration file like connect.properties, please let me known.

Thanks

**Comment by fhussonnois** [comment]
Hi @ccamba, thank you for reporting that issue. I will process CDATA node in the same way as TextNode instead of using `setCoalescing(true)` to be able to filter `\n\t` characters.

Because if we use `setCoalescing(true)`  and for example the input XML is : 

```
<ROOT>\n+\t<![CDATA[dummy text]]>\n</ROOT>
```

Then the content for root is `\n\tdummy text\n`. So it's better to directly get clean output `dummy text`.

I will push a fix very soon.

**Comment by ccamba** [comment]
Thanks @fhussonnois
