### ISSUE TITLE
Mismatched Input Error

### ISSUE THREAD

**Issue by mohai-kafka** [streamthoughts/kafka-connect-file-pulse#66]
Using Kafka Connect File Pulse. When i use JSONFilter and AppendFilter getting following error. Attached my config and sample JSON for reference.
[A_6.txt](https://github.com/streamthoughts/kafka-connect-file-pulse/files/5081721/A_6.txt)

[2020-08-16 21:18:49,161] ERROR [coverage-etl-filepulse-source-connect-deva-1.4.2|task-0] WorkerSourceTask{id=coverage-etl-filepulse-source-connect-deva-1.4.2-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:186)
org.apache.kafka.connect.errors.ConnectException: io.streamthoughts.kafka.connect.filepulse.expression.parser.ScELParseCancellationException: Cannot parse ScEL expression '{{ matches($metadata.name,^A_.*) }}' : line 1:27 mismatched input 'A_' expecting Literal
        at io.streamthoughts.kafka.connect.filepulse.config.TaskConfig.filters(TaskConfig.java:155)
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.newFileRecordsPollingConsumer(FilePulseSourceTask.java:89)
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.start(FilePulseSourceTask.java:81)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:213)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.streamthoughts.kafka.connect.filepulse.expression.parser.ScELParseCancellationException: Cannot parse ScEL expression '{{ matches($metadata.name,^A_.*) }}' : line 1:27 mismatched input 'A_' expecting Literal
        at io.streamthoughts.kafka.connect.filepulse.expression.parser.antlr4.Antlr4ExpressionParser$ThrowingErrorListener.syntaxError(Antlr4ExpressionParser.java:97)
        at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
        at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
        at io.streamthoughts.kafka.connect.filepulse.expression.parser.antlr4.ScELParser.value(ScELParser.java:809)
        at io.streamthoughts.kafka.connect.filepulse.expression.parser.antlr4.ScELParser.functionParameters(ScELParser.java:720)
        at io.streamthoughts.kafka.connect.filepulse.expression.parser.antlr4.ScELParser.functionDeclaration(ScELParser.java:656)
        at io.streamthoughts.kafka.connect.filepulse.expression.parser.antlr4.ScELParser.expression(ScELParser.java:434)
        at io.streamthoughts.kafka.connect.filepulse.expression.parser.antlr4.ScELParser.substitutionStrExpression(ScELParser.java:363)
        at io.streamthoughts.kafka.connect.filepulse.expression.parser.antlr4.ScELParser.substitutionExpression(ScELParser.java:242)
        at io.streamthoughts.kafka.connect.filepulse.expression.parser.antlr4.ScELParser.scel(ScELParser.java:163)
        at io.streamthoughts.kafka.connect.filepulse.expression.parser.antlr4.Antlr4ExpressionParser.parseExpression(Antlr4ExpressionParser.java:72)
        at io.streamthoughts.kafka.connect.filepulse.expression.parser.antlr4.Antlr4ExpressionParser.parseExpression(Antlr4ExpressionParser.java:57)
        at io.streamthoughts.kafka.connect.filepulse.expression.parser.ExpressionParsers.parseExpression(ExpressionParsers.java:37)
        at io.streamthoughts.kafka.connect.filepulse.filter.condition.ExpressionFilterCondition.<init>(ExpressionFilterCondition.java:44)
        at io.streamthoughts.kafka.connect.filepulse.config.CommonFilterConfig.condition(CommonFilterConfig.java:85)
        at io.streamthoughts.kafka.connect.filepulse.filter.AbstractRecordFilter.configure(AbstractRecordFilter.java:50)
        at io.streamthoughts.kafka.connect.filepulse.filter.AbstractMergeRecordFilter.configure(AbstractMergeRecordFilter.java:40)
        at io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter.configure(AppendFilter.java:49)
        at io.streamthoughts.kafka.connect.filepulse.config.TaskConfig.filters(TaskConfig.java:152)
        ... 10 more
[2020-08-16 21:18:49,162] ERROR [coverage-etl-filepulse-source-connect-deva-1.4.2|task-0] WorkerSourceTask{id=coverage-etl-filepulse-source-connect-deva-1.4.2-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:187)

**Comment by fhussonnois** [comment]
Hi @mohai-kafka, change your expression to be `{{ matches($metadata.name,'^A_.*') }}`. This should fixes your issue (note the quotes)

**Comment by mohai-kafka** [comment]
Getting NullPointerError. 

File Name is A_11.json

Filter is : 

   "filters": "SetSUBGRPTopic",
    "filters.SetSUBGRPTopic.field": "{{$topic}}",
    "filters.SetSUBGRPTopic.if": "{{ matches($metadata.name,'^A_.*') }}",
    "filters.SetSUBGRPTopic.override": true,
    "filters.SetSUBGRPTopic.type": "io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter",
    "filters.SetSUBGRPTopic.value": "sampleTopic",


[2020-08-17 22:27:47,085] ERROR [coverage-etl-filepulse-source-connect-deva-1.4.2|task-0] Error occurred while executing filter 'AppendFilter' on record='[message=[value=[B@b5d95ad, schema =[type=BYTES]]]' (io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline:180)
[2020-08-17 22:27:47,085] ERROR [coverage-etl-filepulse-source-connect-deva-1.4.2|task-0] Error while processing source file '[name='A_11.json', path='/opt/kafka/confluent/coveragetmp', size=68, lastModified=1597717633000, inode=6150174, hash=3065395771]' (io.streamthoughts.kafka.connect.filepulse.source.KafkaFileStateReporter:119)
java.lang.NullPointerException
        at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression$ReplacementExpression.readValue(SubstitutionExpression.java:214)
        at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression.readValue(SubstitutionExpression.java:104)
        at io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter.mayEvaluateWriteExpression(AppendFilter.java:105)
        at io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter.apply(AppendFilter.java:81)
        at io.streamthoughts.kafka.connect.filepulse.filter.AbstractMergeRecordFilter.apply(AbstractMergeRecordFilter.java:51)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline$FilterNode.apply(DefaultRecordFilterPipeline.java:159)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:131)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:99)
        at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:169)
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:126)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:270)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:237)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2020-08-17 22:27:47,086] INFO [coverage-etl-filepulse-source-connect-deva-1.4.2|task-0] WorkerSourceTask{id=coverage-etl-filepulse-source-connect-deva-1.4.2-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:424)
[2020-08-17 22:27:47,086] INFO [coverage-etl-filepulse-source-connect-deva-1.4.2|task-0] WorkerSourceTask{id=coverage-etl-filepulse-source-connect-deva-1.4.2-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:441)
[2020-08-17 22:27:47,086] ERROR [coverage-etl-filepulse-source-connect-deva-1.4.2|task-0] WorkerSourceTask{id=coverage-etl-filepulse-source-connect-deva-1.4.2-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:186)
io.streamthoughts.kafka.connect.filepulse.errors.ConnectFilePulseException: java.lang.NullPointerException
        at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:188)
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:126)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:270)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:237)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression$ReplacementExpression.readValue(SubstitutionExpression.java:214)
        at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression.readValue(SubstitutionExpression.java:104)
        at io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter.mayEvaluateWriteExpression(AppendFilter.java:105)
        at io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter.apply(AppendFilter.java:81)
        at io.streamthoughts.kafka.connect.filepulse.filter.AbstractMergeRecordFilter.apply(AbstractMergeRecordFilter.java:51)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline$FilterNode.apply(DefaultRecordFilterPipeline.java:159)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:131)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:99)
        at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:169)
        ... 10 more
[2020-08-17 22:27:47,086] ERROR [coverage-etl-filepulse-source-connect-deva-1.4.2|task-0] WorkerSourceTask{id=coverage-etl-filepulse-source-connect-deva-1.4.2-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:187)

**Comment by fhussonnois** [comment]
Hi @mohai-kafka, thanks, I find the cause for the NPE. But, even if that should not happen your configuration will still throw an error because you have configured the `"filters.SetSUBGRPTopic.field": "{{$topic}}"` with a substitution expression.

The substitution expression `{{ $topi c}}` is evaluated to `null` because the topic is not defined. So, just remove the curly brackets `$topic`.

**Comment by mohai-kafka** [comment]
Still getting NPE. Below is the stack trace and filter condition.

[2020-08-18 07:20:55,440] ERROR [coverage-etl-filepulse-source-connect-deva-1.4.2|task-0] Error occurred while executing filter 'AppendFilter' on record='[message=[value=[B@6cafdb5d, schema =[type=BYTES]]]' (io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline:180)
[2020-08-18 07:20:55,441] ERROR [coverage-etl-filepulse-source-connect-deva-1.4.2|task-0] Error while processing source file '[name='A_11.json', path='/opt/kafka/confluent/coveragetmp', size=68, lastModified=1597717633000, inode=6150174, hash=3065395771]' (io.streamthoughts.kafka.connect.filepulse.source.KafkaFileStateReporter:119)
java.lang.NullPointerException
        at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression$ReplacementExpression.readValue(SubstitutionExpression.java:214)
        at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression.readValue(SubstitutionExpression.java:104)
        at io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter.mayEvaluateWriteExpression(AppendFilter.java:105)
        at io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter.apply(AppendFilter.java:81)
        at io.streamthoughts.kafka.connect.filepulse.filter.AbstractMergeRecordFilter.apply(AbstractMergeRecordFilter.java:51)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline$FilterNode.apply(DefaultRecordFilterPipeline.java:159)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:131)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:99)
        at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:169)
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:126)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:270)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:237)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2020-08-18 07:20:55,443] INFO [coverage-etl-filepulse-source-connect-deva-1.4.2|task-0] WorkerSourceTask{id=coverage-etl-filepulse-source-connect-deva-1.4.2-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:424)
[2020-08-18 07:20:55,443] INFO [coverage-etl-filepulse-source-connect-deva-1.4.2|task-0] WorkerSourceTask{id=coverage-etl-filepulse-source-connect-deva-1.4.2-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:441)


    "filters": "SetSUBGRPTopic",
    "filters.SetSUBGRPTopic.field": "$topic",
    "filters.SetSUBGRPTopic.if": "{{ matches($metadata.name,'^A_.*') }}",
    "filters.SetSUBGRPTopic.override": "true",
    "filters.SetSUBGRPTopic.type": "io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter",
    "filters.SetSUBGRPTopic.value": "sampleTopic",

**Comment by fhussonnois** [comment]
Are you sure the configuration has been updated ? 

Because you get the exception the following exception but `$topic` cannot compile to a `SubstitutionExpression` and 

```
java.lang.NullPointerException
at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression$ReplacementExpression.readValue(SubstitutionExpression.java:214)
at io.streamthoughts.kafka.connect.filepulse.expression.SubstitutionExpression.readValue(SubstitutionExpression.java:104)
at io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter.mayEvaluateWriteExpression(AppendFilter.java:105)
at io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter.apply(AppendFilter.java:81)
```

**Comment by mohai-kafka** [comment]
yes I verified in config method in connector and see $topic . Below is my JSON for connect.

{
  "config": {
    "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
    "filters": "SetSUBGRPTopic",
    "filters.SetSUBGRPTopic.field": "$topic",
    "filters.SetSUBGRPTopic.if": "{{ matches($metadata.name,'^A_.*') }}",
    "filters.SetSUBGRPTopic.override": true,
    "filters.SetSUBGRPTopic.type": "io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter",
    "filters.SetSUBGRPTopic.value": "sampleTopic",
    "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy",
    "fs.scan.directory.path": "/opt/kafka/confluent/coveragetmp",
    "fs.scan.interval.ms": "5000",
    "fs.scanner.class": "io.streamthoughts.kafka.connect.filepulse.scanner.local.LocalFSDirectoryWalker",
    "internal.kafka.reporter.bootstrap.servers": "XXXXXX",
    "internal.kafka.reporter.consumer.sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username='YYYYY' password='YYYYYY';",
    "internal.kafka.reporter.consumer.sasl.mechanism": "PLAIN",
    "internal.kafka.reporter.consumer.security.protocol": "SASL_SSL",
    "internal.kafka.reporter.consumer.ssl.endpoint.identification.algorithm": "https",
    "internal.kafka.reporter.id": "connect-file-pulse-xml",
    "internal.kafka.reporter.producer.sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username='YYYYY' password='YYYYY';",
    "internal.kafka.reporter.producer.sasl.mechanism": "PLAIN",
    "internal.kafka.reporter.producer.security.protocol": "SASL_SSL",
    "internal.kafka.reporter.producer.ssl.endpoint.identification.algorithm": "https",
    "internal.kafka.reporter.topic": "connect-file-pulse-status",
    "offset.strategy": "name+hash",
    "read.max.wait.ms": "5000",
    "task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.BytesArrayInputReader",
    "tasks.max": 1,
    "topic": "sampleTopicRetry1"
  },
  "name": "coverage-etl-filepulse-source-connect-deva-1.4.2"
}

**Comment by fhussonnois** [comment]
OK. I'm sorry but I are you sure this is not an exception from a previous connector ?

I write that test with your configuration and everything is working as expected: 

```java
        // create filter
        AppendFilter filter = new AppendFilter();
        filter.configure(new HashMap<String, String>() {{
            put("field", "$topic");
            put("if", "{{ matches($metadata.name,'^A_.*') }}");
            put("override", "true");
            put("value", "sampleTopic");
        }});

        // Create test context
        FilterContext context = FilterContextBuilder.newBuilder()
                .withMetadata(createSourceMetadata("A_test.txt"))
                .withOffset(FileRecordOffset.invalid())
                .build();

        Assert.assertNull(context.topic());

        // Conditionally execute AppendFilter
        final TypedStruct input = TypedStruct.create();
        if (filter.accept(context, input)) {
            filter.apply(context, input, false);
        }

        // Test passed
        Assert.assertEquals("sampleTopic", context.topic());
```
