### ISSUE TITLE
class not found exception on offset manager

### ISSUE THREAD

**Issue by minnieshi** [streamthoughts/kafka-connect-file-pulse#73]
I have put lots of information here:
https://stackoverflow.com/questions/63796593/kafka-connect-file-pulse-connector-standalone-could-not-startclass-not-found-ex

Please let me know if you need me to copy them over here.

High level summary of the problem:
- below are my environment:
> win10 enterprise WSL, installed Ubuntu

> downloaded the confluent platform 5.5.1 (see "https://www.confluent.io/download/"), unpacked

> downloaded zip file version 1.5.2 from github (https://github.com/streamthoughts/kafka-connect-file-pulse/releases), unzipped

> modified the "connect-standalone.properties" located under confluent path (etc/kafka/connect-standalone.properties) to include path "/home/min/streamthoughts-kafka-connect-file-pulse-1.5.2/lib"

> I did not create any topic.

- I started zookeeper; kafka, and tried to start kafka-connect standalone like below:
`$ zookeeper-server-start etc/kafka/zookeeper.properties`
`$ kafka-server-start etc/kafka/server.properties`
`$ connect-standalone \
etc/kafka/connect-standalone.properties \
/home/min/streamthoughts-kafka-connect-file-pulse-1.5.2/etc/quickstart-connect-file-pulse-csv.properties`

- but I have failures see below
`[2020-09-08 15:57:45,554] INFO Loading plugin from: /home/min/streamthoughts-kafka-connect-file-pulse-1.5.2/lib/kafka-connect-file-pulse-plugin-1.5.2.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:239)
[2020-09-08 15:57:45,575] ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectStandalone:130)
java.lang.NoClassDefFoundError: io/streamthoughts/kafka/connect/filepulse/offset/OffsetManager
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
    at java.lang.Class.getConstructor0(Class.java:3075)
    at java.lang.Class.newInstance(Class.java:412)
    at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.versionFor(DelegatingClassLoader.java:385)
    at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.getPluginDesc(DelegatingClassLoader.java:355)
    at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanPluginPath(DelegatingClassLoader.java:328)
    at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanUrlsAndAddPlugins(DelegatingClassLoader.java:261)
    at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.registerPlugin(DelegatingClassLoader.java:253)
    at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initPluginLoader(DelegatingClassLoader.java:222)
    at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initLoaders(DelegatingClassLoader.java:199)
    at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:60)
    at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:79)
Caused by: java.lang.ClassNotFoundException: io.streamthoughts.kafka.connect.filepulse.offset.OffsetManager
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 13 more
`
- the log shows it did load connect-file-pulse-api, see 
`$ cat log.txt | grep connect-file-pulse-api`
INFO Loading plugin from: /home/min/streamthoughts-kafka-connect-file-pulse-1.5.2/lib/kafka-connect-file-pulse-api-1.5.2.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:239) 
INFO Registered loader: PluginClassLoader{pluginLocation=file:/home/min/streamthoughts-kafka-connect-file-pulse-1.5.2/lib/kafka-connect-file-pulse-api-1.5.2.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:262)

**Comment by ccamba** [comment]
Hi @minnieshi , the configuration file is not correct: /etc/kafka-connect-jdbc/sink-quickstart-sqlite.properties
You must pass the properties file corresponding to file-pulse; for example: quickstart-connect-file-pulse-csv.properties
included in the zip with your own config

**Comment by minnieshi** [comment]
Hi @ccamba , I did use "/home/min/streamthoughts-kafka-connect-file-pulse-1.5.2/etc/quickstart-connect-file-pulse-csv.properties"

I was just testing (after above exception failure) if other connector (jdbc) was working or not.

**Comment by minnieshi** [comment]
Hi @ccamba , 
What I posted on stackoverflow, mentions I also tested jdbc connector without exceptions.

**Comment by minnieshi** [comment]
I found 'work around' or 'solution' for the issues. I've posted the comment/answer in the stakoverflow.

**Comment by fhussonnois** [comment]
Hi @minnieshi, the `plugin.path` should be either configured with a top-level directory containing all installed plugins (e.g `/usr/local/share/kafka/plugins`) or the plugin-directory (i.e: `/home/min/streamthoughts-kafka-connect-file-pulse-1.5.2`).

If your problem is resolved, could you please close this issue.

Thank you

**Comment by minnieshi** [comment]
Thank you very much @fhussonnois .

 Being in Windows WSL + Ubuntu made it difficult for me. 
I could not use the other 2 installation options you wrote in the article on Medium https://link.medium.com/QWcjPJMWD9
So this make it difficult for me to see how the setup should be when using  the manual download option. 

Closing the issue now.
