### ISSUE TITLE
DelimitedRowFilter use naive and incorrect approach to split fields by String.split()

### ISSUE THREAD

**Issue by Hubbitus** [streamthoughts/kafka-connect-file-pulse#96]
Said we have file:
```
Network_Device,Country,City,Office_addr,Floor,Room,Working_place,Network_Device_Port                                                                                                                                                        
EPRUIZHNS0001,Russia,Izhevsk,"Lenina, 150",77 floor,,not for user connection,1
```
It is correctly quoted, but I got exception:
```
io.streamthoughts.kafka.connect.filepulse.filter.FilterException: Error while reading delimited input row. Too large number of fields (9)
        at io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter.buildStructForFields(DelimitedRowFilter.java:133)
        at io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter.apply(DelimitedRowFilter.java:96)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline$FilterNode.apply(DefaultRecordFilterPipeline.java:159)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:131)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:99)
        at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:169)
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:127)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:273)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:240)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Because instead of `Office_addr=Lenina, 150` there appeared 2 values...

Input is perfectly correct CSV file according to [CSV RFC4180](https://tools.ietf.org/html/rfc4180)

I think there should be used [opencsv](http://opencsv.sourceforge.net/) or some other well-supported library for parsing.

**Comment by fhussonnois** [comment]
Hi @Hubbitus, you can actually use a more complex REGEX with the to `DelimitedRowFilter` parse your CSV file : `(?:^|,)(?=[^"]|(")?)"?((?(1)[^"]*|[^,"]*))"?(?=,|$)` .

But, Yes maybe we could provide a dedicated Filter that would be more efficient than the DelimitedRowfilter for CSV parsing.

**Comment by Hubbitus** [comment]
@fhussonnois, thank  you for the answer, but your workaround also does not work:
```
[2020-12-09 12:08:38,020] [org.apache.kafka.common.config.AbstractConfig.logAll(AbstractConfig.java:372)] INFO DelimitedRowFilterConfig values: 
        autoGenerateColumnNames = true
        columns = null
        extractColumnName = headers
        if = null
        ignoreFailure = false
        invert = false
        separator = (?:^|,)(?=[^"]|(")?)"?((?(1)[^"]*|[^,"]*))"?(?=,|$)
        trimColumn = true
        withOnFailure = null
 (io.streamthoughts.kafka.connect.filepulse.config.DelimitedRowFilterConfig:372)
[2020-12-09 12:08:38,024] [org.apache.kafka.common.config.AbstractConfig.logAll(AbstractConfig.java:372)] INFO RowFileInputReaderConfig values: 
        buffer.initial.bytes.size = 4096
        file.encoding = UTF-8
        min.read.records = 1
        read.max.wait.ms = 0
        skip.footers = 0
        skip.headers = 1
 (io.streamthoughts.kafka.connect.filepulse.reader.RowFileInputReaderConfig:372)
[2020-12-09 12:08:38,500] [io.streamthoughts.kafka.connect.filepulse.source.FileSystemMonitorThread.run(FileSystemMonitorThread.java:87)] INFO Waiting 1000 ms to scan for new files. (io.streamthoughts.kafka.connect.filepulse.source.FileSystemMonitorThread:87)
[2020-12-09 12:08:38,852] [io.streamthoughts.kafka.connect.filepulse.source.FileInputIterable.open(FileInputIterable.java:65)] INFO Opening new iterator for source : [name='Russia__Izhevsk__V_Sivkova_150-4.csv', path='/home/pasha/@Projects/@Experiments/ksqlDB/@EPM-SSDL/Network_Device-Location_mapping/Russia/wired', size=57023, lastModified=1607467372000, inode=10314160, hash=554228034] (io.streamthoughts.kafka.connect.filepulse.source.FileInputIterable:65)
[2020-12-09 12:08:38,868] [io.streamthoughts.kafka.connect.filepulse.reader.RowFileInputIterator.mayReadHeaders(RowFileInputIterator.java:281)] INFO Starting to read header lines (1) from file Russia__Izhevsk__V_Sivkova_150-4.csv (io.streamthoughts.kafka.connect.filepulse.reader.RowFileInputIterator:281)
[2020-12-09 12:08:38,891] [io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline$FilterNode.apply(DefaultRecordFilterPipeline.java:180)] ERROR Error occurred while executing filter 'DelimitedRowFilter' on record='[name: message, type: STRING, value: EPRUIZHNS0001,Russia,Izhevsk,"V. Sivkova, 150",4 floor,,not for user connection,1, name: headers, type: ARRAY, value: [Network_Device,Country,City,Office_addr,Floor,Room,Working_place,Network_Device_Port]]' (io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline:180)
[2020-12-09 12:08:38,892] [io.streamthoughts.kafka.connect.filepulse.source.KafkaFileStateReporter.onFailure(KafkaFileStateReporter.java:120)] ERROR Error while processing source file '[name='Russia__Izhevsk__V_Sivkova_150-4.csv', path='/home/pasha/@Projects/@Experiments/ksqlDB/@EPM-SSDL/Network_Device-Location_mapping/Russia/wired', size=57023, lastModified=1607467372000, inode=10314160, hash=554228034]' (io.streamthoughts.kafka.connect.filepulse.source.KafkaFileStateReporter:120)
java.util.regex.PatternSyntaxException: Unknown inline modifier near index 25
(?:^|,)(?=[^"]|(")?)"?((?(1)[^"]*|[^,"]*))"?(?=,|$)
                         ^
        at java.util.regex.Pattern.error(Pattern.java:1969)
        at java.util.regex.Pattern.group0(Pattern.java:2908)
        at java.util.regex.Pattern.sequence(Pattern.java:2065)
        at java.util.regex.Pattern.expr(Pattern.java:2010)
        at java.util.regex.Pattern.group0(Pattern.java:2919)
        at java.util.regex.Pattern.sequence(Pattern.java:2065)
        at java.util.regex.Pattern.expr(Pattern.java:2010)
        at java.util.regex.Pattern.compile(Pattern.java:1702)
        at java.util.regex.Pattern.<init>(Pattern.java:1352)
        at java.util.regex.Pattern.compile(Pattern.java:1028)
        at java.lang.String.split(String.java:2380)
        at java.lang.String.split(String.java:2422)
        at io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter.splitFields(DelimitedRowFilter.java:127)
        at io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter.apply(DelimitedRowFilter.java:94)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline$FilterNode.apply(DefaultRecordFilterPipeline.java:159)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:131)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:99)
        at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:169)
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:127)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:273)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:240)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by fhussonnois** [comment]
@Hubbitus, Yes the regex seems not valid for Java. This one should work : `("(?:[^"]|"")*"|[^,"\n\r]*)(,|\r?\n|\r)`

**Comment by Hubbitus** [comment]
https://regex101.com/r/gDMGYN/1

Prroblem wit that what quotes also captured:
![image](https://user-images.githubusercontent.com/720349/103094271-01494e80-460e-11eb-94ba-406a7791aec6.png)
